var PIECE_NONE=0,PIECE_K=1,PIECE_A=2,PIECE_E=3,PIECE_H=4,PIECE_R=5,PIECE_C=6,PIECE_P=7,PIECE_BK=1,PIECE_BA=2,PIECE_BE=3,PIECE_BH=4,PIECE_BR=5,PIECE_BC=6,PIECE_BP=7,PIECE_RK=9,PIECE_RA=10,PIECE_RE=11,PIECE_RH=12,PIECE_RR=13,PIECE_RC=14,PIECE_RP=15;function isRedPiece(u){return 8<=u}function Move(u,x,e,A,C,v){this.i1=u;this.j1=x;this.i2=e;this.j2=A;this.piece=C||PIECE_NONE;this.capture=v||PIECE_NONE}
function Chess(){function u(){return 0==b.length%2}function x(d){return 8<=d?d-8:d}function e(){m=[];b=[];for(var d=0;10>d;++d)for(m.push([]),j=0;9>j;++j)m[d].push(0);d="rheakaehr 9 1c5c1 p1p1p1p1p 9 9 P1P1P1P1P 1C5C1 9 RHEAKAEHR".split(" ");if(10!=d.length)throw"Malformed fen string: rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";for(i=0;10>i;++i){var p=0;for(k=0;k<d[i].length;++k){if(9<=p)throw"Malformed fen string at row "+i+": rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";
var a=d[i][k];if("0"<=a&&"9">=a)p+=parseInt(d[i][k],10);else{var a=m[i],c=p,g=d[i][k],h=g==g.toLowerCase(),g=g.toLowerCase(),f=0;"k"==g?f=1:"a"==g?f=2:"e"==g?f=3:"h"==g?f=4:"r"==g?f=5:"c"==g?f=6:"p"==g&&(f=7);h||(f+=8);a[c]=f;++p}}}}function A(d,p,a,g){b.push(new Move(d,p,a,g,m[d][p],m[a][g]));m[a][g]=m[d][p];m[d][p]=0;return b[b.length-1]}function C(){var d=b.pop();m[d.i1][d.j1]=m[d.i2][d.j2];m[d.i2][d.j2]=d.capture}function v(d,p){return 0<=d&&10>d&&0<=p&&9>p}function q(d,p){return 3<=p&&5>=p&&
(0<=d&&2>=d||7<=d&&9>=d)}function y(d,p){var b=[];for(r=0;4>r;++r)q(d+a[r],p+g[r])&&b.push(new Move(d,p,d+a[r],p+g[r]));for(delta=-1;1>=delta;delta+=2)for(ii=d+delta;0<=ii&&10>ii&&(x(m[ii][p])==PIECE_K&&b.push(new Move(d,p,ii,p)),0==m[ii][p]);ii+=delta);return b}function B(d,p){var a=[];for(r=0;4>r;++r)q(d+h[r],p+f[r])&&a.push(new Move(d,p,d+h[r],p+f[r]));return a}function D(d,a){var b=[];for(r=0;4>r;++r)v(d+2*h[r],a+2*f[r])&&0==m[d+h[r]][a+f[r]]&&4<d+h[r]&&b.push(new Move(d,a,d+2*h[r],a+2*f[r]));
return b}function w(d,a){var b=[];for(r=0;4>r;++r)!v(d+2*h[r],a+2*f[r])||0!=m[d+h[r]][a+f[r]]||4<d+h[r]||b.push(new Move(d,a,d+2*h[r],a+2*f[r]));return b}function t(d,a){var b=[];[[1,2,0,1],[1,-2,0,-1],[-1,2,0,1],[-1,-2,0,-1],[2,1,1,0],[2,-1,1,0],[-2,1,-1,0],[-2,-1,-1,0]].forEach(function(g){v(d+g[0],a+g[1])&&0==m[d+g[2]][a+g[3]]&&b.push(new Move(d,a,d+g[0],a+g[1]))});return b}function c(d,p){var b=[];for(r=0;4>r;++r){var c,h;c=d+a[r];for(h=p+g[r];v(c,h)&&(b.push(new Move(d,p,c,h)),0==m[c][h]);c+=
a[r],h+=g[r]);}return b}function z(d,p){var b=[];for(r=0;4>r;++r){var c,h,f=!1;c=d+a[r];for(h=p+g[r];v(c,h);c+=a[r],h+=g[r])if(!f&&0==m[c][h])b.push(new Move(d,p,c,h));else if(!f&&0!=m[c][h])f=!0;else if(f&&0!=m[c][h]){b.push(new Move(d,p,c,h));break}}return b}function l(d,a){var b=[];4<d?b.push(new Move(d,a,d-1,a)):(v(d-1,a)&&b.push(new Move(d,a,d-1,a)),v(d,a-1)&&b.push(new Move(d,a,d,a-1)),v(d,a+1)&&b.push(new Move(d,a,d,a+1)));return b}function F(d,a){var b=[];4<d?(v(d+1,a)&&b.push(new Move(d,
a,d+1,a)),v(d,a-1)&&b.push(new Move(d,a,d,a-1)),v(d,a+1)&&b.push(new Move(d,a,d,a+1))):b.push(new Move(d,a,d+1,a));return b}function n(a,b,g){var h=x(m[a][b]),f=isRedPiece(m[a][b]),e=[];1==h?e=y(a,b):2==h?e=B(a,b):3==h?e=f?D(a,b):w(a,b):4==h?e=t(a,b):5==h?e=c(a,b):6==h?e=z(a,b):7==h&&(e=f?l(a,b):F(a,b));e.forEach(function(a){0!=m[a.i2][a.j2]&&isRedPiece(m[a.i2][a.j2])==f||g.push(a)})}function E(a){var b=[];for(i=0;10>i;++i)for(j=0;9>j;++j)0!=m[i][j]&&isRedPiece(m[i][j])==a&&n(i,j,b);return b}this.reset=
e;this.setMoves=function(a){var g=b;e();for(var h=!0,c=0,f=0;f<a.length;++f)A(a[f][0],a[f][1],a[f][2],a[f][3]),h&&g.length>f&&g[f].i1==a[f][0]&&g[f].j1==a[f][1]&&g[f].i2==a[f][2]&&g[f].j2==a[f][3]?++c:h=!1;return c};this.move=A;this.checkMove=function(a,b,g,h){var c=u();if(!E(c).find(function(c,f,e){return c.i1==a&&c.j1==b&&c.i2==g&&c.j2==h}))return!1;if(m[g][h]==(c?PIECE_BK:PIECE_RK))return!0;var f=!1;A(a,b,g,h);E(!c).find(function(a,b,d){return m[a.i2][a.j2]==(c?PIECE_RK:PIECE_BK)})&&(f=!0);C();
return!f};this.moveHistory=function(){for(var a=[],g=0;g<b.length;++g)a.push(b[g]);return a};this.pieceAt=function(a,b){return m[a][b]};this.isRedNext=u;this.numMoves=function(){return b.length};var m=[],b=[];e();var a=[0,1,0,-1],g=[1,0,-1,0],h=[1,1,-1,-1],f=[1,-1,-1,1]};function removeAllChildren(u){for(u=document.getElementById(u);u.lastChild;)u.removeChild(u.lastChild)}
function BoardUI(u){function x(){return document.getElementById("board")}function e(b,a){m&&(a=8-a);return n/2+a*n}function A(b,a){m&&(b=9-b);return 5>a?n/2+b*n:n/2+b*n+E}function C(b,a,g,c,f,d){var e=document.createElementNS(l,"line");e.setAttribute("x1",b);e.setAttribute("y1",a);e.setAttribute("x2",g);e.setAttribute("y2",c);e.setAttribute("class",f);d&&(e.id=d);return e}function v(b,a,g,c,f){var d=e(b,a);b=A(b,a);a=document.createElementNS(l,"circle");a.setAttribute("cx",d);a.setAttribute("cy",
b);a.setAttribute("r",g);a.setAttribute("class",c);f&&(a.id=f);return a}function q(b,a){return"abcdefghi"[a]+(9-b).toString()}function y(b,a){return function(){u(b,a)}}function B(b,a){var g=v(b,a,23,"piece-cover","piece-cover-"+q(b,a));g.style.strokeWidth=0;g.style.fillOpacity=0;g.onmousedown=y(b,a);g.touchend=g.onmousedown;w(g)}function D(b,a){var g="piece-cover-"+q(b,a);null!=document.getElementById(g)&&t(g)}function w(b){x().appendChild(b)}function t(b){x().removeChild(document.getElementById(b))}
function c(b,a,g,c){var f;f=e(b,a);b=A(b,a);a=e(g,c);g=A(g,c);f=C(f,b,a,g,"grid",void 0);f.style.strokeWidth=1;f.style.stroke="gray";w(f)}function z(b){m=b;removeAllChildren("board");x();for(i=0;9>i;++i)c(0,i,4,i),0!=i&&8!=i||c(4,i,5,i),c(5,i,9,i);for(i=0;10>i;++i)c(i,0,i,8);c(0,3,2,5);c(0,5,2,3);c(7,3,9,5);c(9,3,7,5);for(i=0;10>i;++i)for(j=0;9>j;++j)B(i,j)}this.reset=z;this.drawPiece=function(b,a,c){D(b,a);var h=v(b,a,23,"piece-outer","piece-outer-"+q(b,a)),f=v(b,a,20,"piece-inner","piece-inner-"+
q(b,a)),d=F[c],z="piece-text-"+q(b,a),m=e(b,a)-12,t=A(b,a)+7.5,n=document.createElementNS(l,"text");n.style.fontSize=24;n.setAttribute("x",m);n.setAttribute("y",t);n.appendChild(document.createTextNode(d));n.setAttribute("class","piece-text");z&&(n.id=z);isRedPiece(c)?(h.setAttribute("stroke","red"),f.style.stroke="red",n.style.fill="red"):(h.style.stroke="black",f.style.stroke="black",n.style.fill="black");h.style.strokeWidth=2;f.style.strokeWidth=2;h.style.fill="white";f.style.fillOpacity=0;w(h);
w(f);w(n);B(b,a)};this.erasePiece=function(b,a){D(b,a);t("piece-text-"+q(b,a));t("piece-inner-"+q(b,a));t("piece-outer-"+q(b,a));B(b,a)};this.highlightSquare=function(b,a){var c=e(b,a),h=A(b,a),f=n/6;for(b=-1;1>=b;b+=2){var d=C(c-23,h+23*b,c-23+f,h+23*b,"highlighter",void 0);d.style.strokeWidth=2;d.style.stroke="blue";w(d);d=C(c+23-f,h+23*b,c+23,h+23*b,"highlighter",void 0);d.style.strokeWidth=2;d.style.stroke="blue";w(d)}for(b=-1;1>=b;b+=2)d=C(c+23*b,h-23,c+23*b,h-23+f,"highlighter",void 0),d.style.strokeWidth=
2,d.style.stroke="blue",w(d),d=C(c+23*b,h+23-f,c+23*b,h+23,"highlighter",void 0),d.style.strokeWidth=2,d.style.stroke="blue",w(d)};this.eraseHighlights=function(){for(var b=x().getElementsByClassName("highlighter");0<b.length;)x().removeChild(b[0])};var l="http://www.w3.org/2000/svg",F=" \u5c07 \u58eb \u8c61 \u99ac \u8eca \u7832 \u5352  \u5e25 \u4ed5 \u76f8 \u508c \u4fe5 \u70ae \u5175".split(" "),n=50,E=0,m=!1;z(!1)};function Board(u){function x(){for(var c=0;10>c;++c)for(var e=0;9>e;++e)q.pieceAt(c,e)!=PIECE_NONE&&y.drawPiece(c,e,q.pieceAt(c,e));t=q.numMoves()}function e(c){c=Math.max(0,c);c=Math.min(q.numMoves(),c);if(c!=t){var e=q.moveHistory();if(c>t)for(var l=t;l<c;++l)C(e[l]);else for(l=t-1;l>=c;--l)0<l?v(e[l],e[l-1]):v(e[l],null);t=c}}function A(c){return c==PIECE_NONE?!1:"r"==B?isRedPiece(c):"b"==B?!isRedPiece(c):!1}function C(c){y.erasePiece(c.i1,c.j1);c.capture&&y.erasePiece(c.i2,c.j2);y.drawPiece(c.i2,
c.j2,c.piece);y.eraseHighlights();y.highlightSquare(c.i1,c.j1);y.highlightSquare(c.i2,c.j2);w=null}function v(c,e){y.drawPiece(c.i1,c.j1,c.piece);y.erasePiece(c.i2,c.j2);c.capture&&y.drawPiece(c.i2,c.j2,c.capture);y.eraseHighlights();e&&(y.highlightSquare(e.i1,e.j1),y.highlightSquare(e.i2,e.j2));w=null}this.setState=function(c,z,l){c!=B&&(B=c,y.reset("b"==c),q.reset(),x(),w=null);D=z;c=q.moveHistory();l=q.setMoves(l);z=t;t==c.length&&(z=q.numMoves());for(z=Math.min(z,q.numMoves());t>l;--t){var u=
t-1;0<u?v(c[u],c[u-1]):v(c[u],null)}e(z)};this.showMove=e;this.isRedNext=function(){return q.isRedNext()};this.numMoves=function(){return q.numMoves()};this.numMovesShown=function(){return t};var q=new Chess,y=new BoardUI(function(c,e){if(!D){var l=q.isRedNext();if(("r"==B&&l||"b"==B&&!l)&&t==q.numMoves())if(w)if(q.checkMove(w[0],w[1],c,e)){var l=w[0],v=w[1];C(q.move(l,v,c,e));++t;u(l,v,c,e)}else A(q.pieceAt(c,e))&&(y.eraseHighlights(),w=[c,e],y.highlightSquare(c,e));else A(q.pieceAt(c,e))&&(y.eraseHighlights(),
w=[c,e],y.highlightSquare(c,e))}}),B="r",D=!0,w=null,t=0;x()};String.prototype.endsWith||(String.prototype.endsWith=function(u,x){var e=this.toString();if(void 0===x||x>e.length)x=e.length;x-=u.length;e=e.indexOf(u,x);return-1!==e&&e===x});
function Game(u,x,e){function A(a,c,h,f,d,e,n){var l=new XMLHttpRequest;l.onreadystatechange=function(){if(4==l.readyState){var a=b.indexOf(h);if(-1!=a){b.splice(a,1);for(var d=E+1;d<=m;++d)if(a=b.indexOf(d),-1==a)E=d;else break;requestResolved=!0}else requestResolved=!1;200<=l.status&&299>=l.status?requestResolved||m==h?e(l.responseText):console.log("Dropped response from an old request."):n&&n(l.responseText)}};l.open(a,c,!0);f&&l.setRequestHeader("Content-type",f);d?l.send(d):l.send()}function C(a,
c,e,f){++m;b.push(m);A("POST",a,m,"application/x-www-form-urlencoded; charset=UTF-8",c,e,f)}function v(a){if("fail"==a)alert("Operation failed");else try{var b=JSON.parse(a);b.gameinfo&&("success"!==b.status&&console.log("last update failed"),b=b.gameinfo);e=b;F()}catch(c){console.log("Unrecognized server response: "+a)}}function q(a){a=a.split("/");for(var b=[],c=1;c<a.length;++c){var f=a[c];if("R"==f||"B"==f)break;b.push([parseInt(f[0],10),parseInt(f[1],10),parseInt(f[2],10),parseInt(f[3],10)])}return b}
function y(a,b,c,f){var d=e;a=[a,b,c,f];d.moves+="/"+(""+a[0]+a[1]+a[2]+a[3]);C("/gameinfo","sid="+D("sid")+"&gid="+u+"&moves="+e.moves,v,B);l()}function B(a){console.log("Retrieve game info failed")}function D(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;++c){for(var f=b[c];" "==f.charAt(0);)f=f.substring(1);if(0==f.indexOf(a))return f.substring(a.length,f.length)}return""}function w(a){var b=document.getElementById(a+"-player"),c=document.getElementById(a+"-sit-link");b.removeChild(c);
b.appendChild(document.createTextNode("sitting down..."));C("/gameinfo","sid="+D("sid")+"&gid="+u+"&sit="+a,v,B)}function t(a,b,c,f,d){var e=document.createElement("a");e.id=a;b&&(e.className=b);e.href=c;f&&(e.onclick=f);e.appendChild(document.createTextNode(d));return e}function c(){removeAllChildren("red-player");removeAllChildren("black-player");if(void 0!==e.red&&null!==e.red){var a="";e.red.id==x&&(a=" (you)");document.getElementById("red-player").appendChild(document.createTextNode("Red: "+
e.red.name+a))}else document.getElementById("red-player").appendChild(document.createTextNode("Red: ")),a=t("red-sit-link",void 0,"#",function(){w("red");return!1},"sit here"),document.getElementById("red-player").appendChild(a);void 0!==e.black&&null!==e.black?(a="",e.black.id==x&&(a=" (you)"),document.getElementById("black-player").appendChild(document.createTextNode("Black: "+e.black.name+a))):(document.getElementById("black-player").appendChild(document.createTextNode("Black: ")),a=t("black-sit-link",
void 0,"#",function(){w("black");return!1},"sit here"),document.getElementById("black-player").appendChild(a))}function z(a,b){var c=document.createElement("td");c.appendChild(b);a.appendChild(c)}function l(){removeAllChildren("move-history");var a=document.getElementById("move-history"),b=document.createElement("table");b.id="moveHistoryControls";var c=document.createElement("tr");b.appendChild(c);0<n.numMovesShown()?(z(c,t("move-history-first",void 0,"#",function(){n.showMove(0);l();return!1},"first")),
z(c,t("move-history-prev",void 0,"#",function(){n.showMove(n.numMovesShown()-1);l();return!1},"prev"))):(z(c,document.createTextNode("first")),z(c,document.createTextNode("prev")));z(c,document.createTextNode(""+n.numMovesShown()+" / "+n.numMoves()));n.numMovesShown()<n.numMoves()?(z(c,t("move-history-next",void 0,"#",function(){n.showMove(n.numMovesShown()+1);l();return!1},"next")),z(c,t("move-history-last",void 0,"#",function(){n.showMove(n.numMoves());l();return!1},"last"))):(z(c,document.createTextNode("next")),
z(c,document.createTextNode("last")));a.appendChild(b);b=document.createElement("div");b.id="moveHistoryFork";b.appendChild(t("move-history-fork-link",void 0,"/fork/"+u+"/"+n.numMovesShown().toString(),void 0,"fork"));b.appendChild(document.createTextNode(" this game from here"));a.appendChild(b)}function F(){c();var a="r";e.black&&e.black.id==x&&(a="b");n.setState(a,!(e.red&&e.black&&!e.moves.endsWith("R")&&!e.moves.endsWith("B")),q(e.moves));removeAllChildren("status");a=document.getElementById("status");
e.moves.endsWith("R")?a.appendChild(document.createTextNode("Red won")):e.moves.endsWith("B")?a.appendChild(document.createTextNode("Black won")):e.red&&e.black?n.isRedNext()?a.appendChild(document.createTextNode("Red to go")):a.appendChild(document.createTextNode("Black to go")):a.appendChild(document.createTextNode("Waiting for players to join..."));l()}var n,E=0,m=0,b=[];(function(){n=new Board(y);F();window.setInterval(function(){A("GET","/gameinfo?gid="+u,E,void 0,void 0,v,B)},1E3)})()}
document.onreadystatechange=function(){"interactive"==document.readyState&&new Game(currentGameId,myUid,gameInfo)};
