var PIECE_NONE=0,PIECE_K=1,PIECE_A=2,PIECE_E=3,PIECE_H=4,PIECE_R=5,PIECE_C=6,PIECE_P=7,PIECE_BK=1,PIECE_BA=2,PIECE_BE=3,PIECE_BH=4,PIECE_BR=5,PIECE_BC=6,PIECE_BP=7,PIECE_RK=9,PIECE_RA=10,PIECE_RE=11,PIECE_RH=12,PIECE_RR=13,PIECE_RC=14,PIECE_RP=15;function isRedPiece(q){return 8<=q}function Move(q,m,d,v,z,t){this.i1=q;this.j1=m;this.i2=d;this.j2=v;this.piece=z||PIECE_NONE;this.capture=t||PIECE_NONE}
function Chess(){function q(){return 0==c.length%2}function m(b){return 8<=b?b-8:b}function d(){e=[];c=[];for(var b=0;10>b;++b)for(e.push([]),j=0;9>j;++j)e[b].push(0);b="rheakaehr 9 1c5c1 p1p1p1p1p 9 9 P1P1P1P1P 1C5C1 9 RHEAKAEHR".split(" ");if(10!=b.length)throw"Malformed fen string: rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";for(i=0;10>i;++i){var h=0;for(k=0;k<b[i].length;++k){if(9<=h)throw"Malformed fen string at row "+i+": rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";
var n=b[i][k];if("0"<=n&&"9">=n)h+=parseInt(b[i][k],10);else{var n=e[i],a=h,B=b[i][k],f=B==B.toLowerCase(),B=B.toLowerCase(),d=0;"k"==B?d=1:"a"==B?d=2:"e"==B?d=3:"h"==B?d=4:"r"==B?d=5:"c"==B?d=6:"p"==B&&(d=7);f||(d+=8);n[a]=d;++h}}}}function v(b,h,n,a){c.push(new Move(b,h,n,a,e[b][h],e[n][a]));e[n][a]=e[b][h];e[b][h]=0;return c[c.length-1]}function z(){var b=c.pop();e[b.i1][b.j1]=e[b.i2][b.j2];e[b.i2][b.j2]=b.capture}function t(b,h){return 0<=b&&10>b&&0<=h&&9>h}function p(b,h){return 3<=h&&5>=h&&
(0<=b&&2>=b||7<=b&&9>=b)}function g(b,h){var c=[];for(r=0;4>r;++r)p(b+n[r],h+x[r])&&c.push(new Move(b,h,b+n[r],h+x[r]));for(delta=-1;1>=delta;delta+=2)for(ii=b+delta;0<=ii&&10>ii&&(m(e[ii][h])==PIECE_K&&c.push(new Move(b,h,ii,h)),0==e[ii][h]);ii+=delta);return c}function y(b,h){var c=[];for(r=0;4>r;++r)p(b+C[r],h+G[r])&&c.push(new Move(b,h,b+C[r],h+G[r]));return c}function D(b,h){var c=[];for(r=0;4>r;++r)t(b+2*C[r],h+2*G[r])&&0==e[b+C[r]][h+G[r]]&&4<b+C[r]&&c.push(new Move(b,h,b+2*C[r],h+2*G[r]));
return c}function u(b,h){var c=[];for(r=0;4>r;++r)!t(b+2*C[r],h+2*G[r])||0!=e[b+C[r]][h+G[r]]||4<b+C[r]||c.push(new Move(b,h,b+2*C[r],h+2*G[r]));return c}function w(b,h){var c=[];[[1,2,0,1],[1,-2,0,-1],[-1,2,0,1],[-1,-2,0,-1],[2,1,1,0],[2,-1,1,0],[-2,1,-1,0],[-2,-1,-1,0]].forEach(function(n){t(b+n[0],h+n[1])&&0==e[b+n[2]][h+n[3]]&&c.push(new Move(b,h,b+n[0],h+n[1]))});return c}function a(b,h){var c=[];for(r=0;4>r;++r){var a,f;a=b+n[r];for(f=h+x[r];t(a,f)&&(c.push(new Move(b,h,a,f)),0==e[a][f]);a+=
n[r],f+=x[r]);}return c}function l(b,h){var c=[];for(r=0;4>r;++r){var a,f,d=!1;a=b+n[r];for(f=h+x[r];t(a,f);a+=n[r],f+=x[r])if(!d&&0==e[a][f])c.push(new Move(b,h,a,f));else if(!d&&0!=e[a][f])d=!0;else if(d&&0!=e[a][f]){c.push(new Move(b,h,a,f));break}}return c}function E(b,c){var a=[];4<b?a.push(new Move(b,c,b-1,c)):(t(b-1,c)&&a.push(new Move(b,c,b-1,c)),t(b,c-1)&&a.push(new Move(b,c,b,c-1)),t(b,c+1)&&a.push(new Move(b,c,b,c+1)));return a}function F(b,c){var a=[];4<b?(t(b+1,c)&&a.push(new Move(b,
c,b+1,c)),t(b,c-1)&&a.push(new Move(b,c,b,c-1)),t(b,c+1)&&a.push(new Move(b,c,b,c+1))):a.push(new Move(b,c,b+1,c));return a}function A(b,c,n){var f=m(e[b][c]),d=isRedPiece(e[b][c]),x=[];1==f?x=g(b,c):2==f?x=y(b,c):3==f?x=d?D(b,c):u(b,c):4==f?x=w(b,c):5==f?x=a(b,c):6==f?x=l(b,c):7==f&&(x=d?E(b,c):F(b,c));x.forEach(function(b){0!=e[b.i2][b.j2]&&isRedPiece(e[b.i2][b.j2])==d||n.push(b)})}function f(b){var c=[];for(i=0;10>i;++i)for(j=0;9>j;++j)0!=e[i][j]&&isRedPiece(e[i][j])==b&&A(i,j,c);return c}this.reset=
d;this.setMoves=function(b){var a=c;d();for(var n=!0,f=0,e=0;e<b.length;++e)v(b[e][0],b[e][1],b[e][2],b[e][3]),n&&a.length>e&&a[e].i1==b[e][0]&&a[e].j1==b[e][1]&&a[e].i2==b[e][2]&&a[e].j2==b[e][3]?++f:n=!1;return f};this.move=v;this.checkMove=function(b,c,a,n){var d=q();if(!f(d).find(function(f,e,d){return f.i1==b&&f.j1==c&&f.i2==a&&f.j2==n}))return!1;if(e[a][n]==(d?PIECE_BK:PIECE_RK))return!0;var x=!1;v(b,c,a,n);f(!d).find(function(b,c,a){return e[b.i2][b.j2]==(d?PIECE_RK:PIECE_BK)})&&(x=!0);z();
return!x};this.moveHistory=function(){for(var b=[],a=0;a<c.length;++a)b.push(c[a]);return b};this.pieceAt=function(b,c){return e[b][c]};this.isRedNext=q;this.numMoves=function(){return c.length};var e=[],c=[];d();var n=[0,1,0,-1],x=[1,0,-1,0],C=[1,1,-1,-1],G=[1,-1,-1,1]};function removeAllChildren(q){for(q=document.getElementById(q);q.lastChild;)q.removeChild(q.lastChild)}
function BoardUI(q){function m(){return document.getElementById("board")}function d(c,a){e&&(a=8-a);return A/2+a*A}function v(c,a){e&&(c=9-c);return 5>a?A/2+c*A:A/2+c*A+f}function z(c,a,f,e,d,b){var h=document.createElementNS(E,"line");h.setAttribute("x1",c);h.setAttribute("y1",a);h.setAttribute("x2",f);h.setAttribute("y2",e);h.setAttribute("class",d);b&&(h.id=b);return h}function t(c,a,f,e,l){var b=d(c,a);c=v(c,a);a=document.createElementNS(E,"circle");a.setAttribute("cx",b);a.setAttribute("cy",
c);a.setAttribute("r",f);a.setAttribute("class",e);l&&(a.id=l);return a}function p(c,a){return"abcdefghi"[a]+(9-c).toString()}function g(c,a){return function(){q(c,a)}}function y(c,a){var f=t(c,a,23,"piece-cover","piece-cover-"+p(c,a));f.style.strokeWidth=0;f.style.fillOpacity=0;f.onmousedown=g(c,a);f.touchend=f.onmousedown;u(f)}function D(c,a){var f="piece-cover-"+p(c,a);null!=document.getElementById(f)&&w(f)}function u(c){m().appendChild(c)}function w(c){m().removeChild(document.getElementById(c))}
function a(c,a,f,e){var l;l=d(c,a);c=v(c,a);a=d(f,e);f=v(f,e);l=z(l,c,a,f,"grid",void 0);l.style.strokeWidth=1;l.style.stroke="gray";u(l)}function l(c){e=c;removeAllChildren("board");m();for(i=0;9>i;++i)a(0,i,4,i),0!=i&&8!=i||a(4,i,5,i),a(5,i,9,i);for(i=0;10>i;++i)a(i,0,i,8);a(0,3,2,5);a(0,5,2,3);a(7,3,9,5);a(9,3,7,5);for(i=0;10>i;++i)for(j=0;9>j;++j)y(i,j)}this.reset=l;this.drawPiece=function(c,a,f){D(c,a);var e=t(c,a,23,"piece-outer","piece-outer-"+p(c,a)),l=t(c,a,20,"piece-inner","piece-inner-"+
p(c,a)),b=F[f],h="piece-text-"+p(c,a),m=d(c,a)-12,q=v(c,a)+7.5,g=document.createElementNS(E,"text");g.style.fontSize=24;g.setAttribute("x",m);g.setAttribute("y",q);g.appendChild(document.createTextNode(b));g.setAttribute("class","piece-text");h&&(g.id=h);isRedPiece(f)?(e.setAttribute("stroke","red"),l.style.stroke="red",g.style.fill="red"):(e.style.stroke="black",l.style.stroke="black",g.style.fill="black");e.style.strokeWidth=2;l.style.strokeWidth=2;e.style.fill="white";l.style.fillOpacity=0;u(e);
u(l);u(g);y(c,a)};this.erasePiece=function(a,f){D(a,f);w("piece-text-"+p(a,f));w("piece-inner-"+p(a,f));w("piece-outer-"+p(a,f));y(a,f)};this.highlightSquare=function(a,f){var e=d(a,f),l=v(a,f),g=A/6;for(a=-1;1>=a;a+=2){var b=z(e-23,l+23*a,e-23+g,l+23*a,"highlighter",void 0);b.style.strokeWidth=2;b.style.stroke="blue";u(b);b=z(e+23-g,l+23*a,e+23,l+23*a,"highlighter",void 0);b.style.strokeWidth=2;b.style.stroke="blue";u(b)}for(a=-1;1>=a;a+=2)b=z(e+23*a,l-23,e+23*a,l-23+g,"highlighter",void 0),b.style.strokeWidth=
2,b.style.stroke="blue",u(b),b=z(e+23*a,l+23-g,e+23*a,l+23,"highlighter",void 0),b.style.strokeWidth=2,b.style.stroke="blue",u(b)};this.eraseHighlights=function(){for(var a=m().getElementsByClassName("highlighter");0<a.length;)m().removeChild(a[0])};var E="http://www.w3.org/2000/svg",F=" \u5c07 \u58eb \u8c61 \u99ac \u8eca \u7832 \u5352  \u5e25 \u4ed5 \u76f8 \u508c \u4fe5 \u70ae \u5175".split(" "),A=50,f=0,e=!1;l(!1)};function Board(q){function m(){for(var a=0;10>a;++a)for(var d=0;9>d;++d)p.pieceAt(a,d)!=PIECE_NONE&&g.drawPiece(a,d,p.pieceAt(a,d));w=p.numMoves()}function d(a){a=Math.max(0,a);a=Math.min(p.numMoves(),a);if(a!=w){var d=p.moveHistory();if(a>w)for(var g=w;g<a;++g)z(d[g]);else for(g=w-1;g>=a;--g)0<g?t(d[g],d[g-1]):t(d[g],null);w=a}}function v(a){return a==PIECE_NONE?!1:"r"==y?isRedPiece(a):"b"==y?!isRedPiece(a):!1}function z(a){g.erasePiece(a.i1,a.j1);a.capture&&g.erasePiece(a.i2,a.j2);g.drawPiece(a.i2,
a.j2,a.piece);g.eraseHighlights();g.highlightSquare(a.i1,a.j1);g.highlightSquare(a.i2,a.j2);u=null}function t(a,d){g.drawPiece(a.i1,a.j1,a.piece);g.erasePiece(a.i2,a.j2);a.capture&&a.drawPiece(a.i2,a.j2.move.capture);g.eraseHighlights();d&&(g.highlightSquare(d.i1,d.j1),g.highlightSquare(d.i2,d.j2));u=null}this.setState=function(a,l,q){a!=y&&(y=a,g.reset("b"==a),p.reset(),m(),u=null);D=l;a=p.moveHistory();q=p.setMoves(q);l=w;w==a.length&&(l=p.numMoves());for(l=Math.min(l,p.numMoves());w>q;--w){var v=
w-1;0<v?t(a[v],a[v-1]):t(a[v],null)}d(l)};this.showMove=d;this.isRedNext=function(){return p.isRedNext()};var p=new Chess,g=new BoardUI(function(a,d){if(!D){var m=p.isRedNext();if(("r"==y&&m||"b"==y&&!m)&&w==p.numMoves())if(u)if(p.checkMove(u[0],u[1],a,d)){var m=u[0],t=u[1];z(p.move(m,t,a,d));++w;q(m,t,a,d)}else v(p.pieceAt(a,d))&&(g.eraseHighlights(),u=[a,d],g.highlightSquare(a,d));else v(p.pieceAt(a,d))&&(g.eraseHighlights(),u=[a,d],g.highlightSquare(a,d))}}),y="r",D=!0,u=null,w=0;m()};String.prototype.endsWith||(String.prototype.endsWith=function(q,m){var d=this.toString();if(void 0===m||m>d.length)m=d.length;m-=q.length;d=d.indexOf(q,m);return-1!==d&&d===m});
function Game(q,m,d){function v(a,d,c,n,g,l,m){var b=new XMLHttpRequest;b.onreadystatechange=function(){if(4==b.readyState){var a=A.indexOf(c);if(-1!=a){A.splice(a,1);for(var f=E+1;f<=F;++f)if(a=A.indexOf(f),-1==a)E=f;else break;requestResolved=!0}else requestResolved=!1;200<=b.status&&299>=b.status?requestResolved||F==c?l(b.responseText):console.log("Dropped response from an old request."):m&&m(b.responseText)}};b.open(a,d,!0);n&&b.setRequestHeader("Content-type",n);g?b.send(g):b.send()}function z(a,
d,c,g){++F;A.push(F);v("POST",a,F,"application/x-www-form-urlencoded; charset=UTF-8",d,c,g)}function t(f){if("fail"==f)alert("Operation failed");else try{var e=JSON.parse(f);e.gameinfo&&("success"!==e.status&&console.log("last update failed"),e=e.gameinfo);d=e;a()}catch(c){console.log("Unrecognized server response: "+f)}}function p(a){a=a.split("/");for(var d=[],c=1;c<a.length;++c){var g=a[c];if("R"==g||"B"==g)break;d.push([parseInt(g[0],10),parseInt(g[1],10),parseInt(g[2],10),parseInt(g[3],10)])}return d}
function g(a,e,c,g){var l=d;a=[a,e,c,g];l.moves+="/"+(""+a[0]+a[1]+a[2]+a[3]);z("/gameinfo","sid="+D("sid")+"&gid="+q+"&moves="+d.moves,t,y)}function y(a){console.log("Retrieve game info failed")}function D(a){a+="=";for(var d=document.cookie.split(";"),c=0;c<d.length;++c){for(var g=d[c];" "==g.charAt(0);)g=g.substring(1);if(0==g.indexOf(a))return g.substring(a.length,g.length)}return""}function u(a){var d=document.getElementById(a+"-player"),c=document.getElementById(a+"-sit-link");d.removeChild(c);
d.appendChild(document.createTextNode("sitting down..."));z("/gameinfo","sid="+D("sid")+"&gid="+q+"&sit="+a,t,y)}function w(){removeAllChildren("red-player");removeAllChildren("black-player");if(void 0!==d.red&&null!==d.red){var a="";d.red.id==m&&(a=" (you)");document.getElementById("red-player").appendChild(document.createTextNode("Red: "+d.red.name+a))}else document.getElementById("red-player").appendChild(document.createTextNode("Red: ")),a=document.createElement("a"),a.id="red-sit-link",a.href=
"#",a.onclick=function(){u("red");return!1},a.appendChild(document.createTextNode("sit here")),document.getElementById("red-player").appendChild(a);void 0!==d.black&&null!==d.black?(a="",d.black.id==m&&(a=" (you)"),document.getElementById("black-player").appendChild(document.createTextNode("Black: "+d.black.name+a))):(document.getElementById("black-player").appendChild(document.createTextNode("Black: ")),a=document.createElement("a"),a.id="black-sit-link",a.href="#",a.onclick=function(){u("black");
return!1},a.appendChild(document.createTextNode("sit here")),document.getElementById("black-player").appendChild(a))}function a(){w();var a="r";d.black&&d.black.id==m&&(a="b");l.setState(a,!(d.red&&d.black&&!d.moves.endsWith("R")&&!d.moves.endsWith("B")),p(d.moves));removeAllChildren("status");a=document.getElementById("status");d.red&&d.black?d.moves.endsWith("R")?a.appendChild(document.createTextNode("Red won")):d.moves.endsWith("B")?a.appendChild(document.createTextNode("Black won")):l.isRedNext()?
a.appendChild(document.createTextNode("Red to go")):a.appendChild(document.createTextNode("Black to go")):a.appendChild(document.createTextNode("Waiting for players to join..."))}var l,E=0,F=0,A=[];(function(){l=new Board(g);a();window.setInterval(function(){v("GET","/gameinfo?gid="+q,E,void 0,void 0,t,y)},1E3)})()}document.onreadystatechange=function(){"interactive"==document.readyState&&new Game(currentGameId,myUid,gameInfo)};
