var PIECE_NONE=0,PIECE_K=1,PIECE_A=2,PIECE_E=3,PIECE_H=4,PIECE_R=5,PIECE_C=6,PIECE_P=7,PIECE_BK=1,PIECE_BA=2,PIECE_BE=3,PIECE_BH=4,PIECE_BR=5,PIECE_BC=6,PIECE_BP=7,PIECE_RK=9,PIECE_RA=10,PIECE_RE=11,PIECE_RH=12,PIECE_RR=13,PIECE_RC=14,PIECE_RP=15;function isRedPiece(w){return 8<=w}function Move(w,l,f,B,D,x){this.i1=w;this.j1=l;this.i2=f;this.j2=B;this.piece=D||PIECE_NONE;this.capture=x||PIECE_NONE}
function Chess(){function w(){return 0==A.length%2}function l(b){return 8<=b?b-8:b}function f(){p=[];A=[];for(var b=0;10>b;++b)for(p.push([]),j=0;9>j;++j)p[b].push(0);b="rheakaehr 9 1c5c1 p1p1p1p1p 9 9 P1P1P1P1P 1C5C1 9 RHEAKAEHR".split(" ");if(10!=b.length)throw"Malformed fen string: rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";for(i=0;10>i;++i){var h=0;for(k=0;k<b[i].length;++k){if(9<=h)throw"Malformed fen string at row "+i+": rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";
var a=b[i][k];if("0"<=a&&"9">=a)h+=parseInt(b[i][k],10);else{var a=p[i],d=h,e=b[i][k],c=e==e.toLowerCase(),e=e.toLowerCase(),g=0;"k"==e?g=1:"a"==e?g=2:"e"==e?g=3:"h"==e?g=4:"r"==e?g=5:"c"==e?g=6:"p"==e&&(g=7);c||(g+=8);a[d]=g;++h}}}}function B(b,h,a,e){A.push(new Move(b,h,a,e,p[b][h],p[a][e]));p[a][e]=p[b][h];p[b][h]=0;return A[A.length-1]}function D(){var b=A.pop();p[b.i1][b.j1]=p[b.i2][b.j2];p[b.i2][b.j2]=b.capture}function x(b,h){return 0<=b&&10>b&&0<=h&&9>h}function z(b,h){return 3<=h&&5>=h&&
(0<=b&&2>=b||7<=b&&9>=b)}function y(b,h){var e=[];for(r=0;4>r;++r)z(b+d[r],h+a[r])&&e.push(new Move(b,h,b+d[r],h+a[r]));for(delta=-1;1>=delta;delta+=2)for(ii=b+delta;0<=ii&&10>ii&&(l(p[ii][h])==PIECE_K&&e.push(new Move(b,h,ii,h)),0==p[ii][h]);ii+=delta);return e}function q(b,h){var a=[];for(r=0;4>r;++r)z(b+e[r],h+g[r])&&a.push(new Move(b,h,b+e[r],h+g[r]));return a}function E(b,h){var a=[];for(r=0;4>r;++r)x(b+2*e[r],h+2*g[r])&&0==p[b+e[r]][h+g[r]]&&4<b+e[r]&&a.push(new Move(b,h,b+2*e[r],h+2*g[r]));
return a}function C(b,h){var a=[];for(r=0;4>r;++r)!x(b+2*e[r],h+2*g[r])||0!=p[b+e[r]][h+g[r]]||4<b+e[r]||a.push(new Move(b,h,b+2*e[r],h+2*g[r]));return a}function u(b,h){var a=[];[[1,2,0,1],[1,-2,0,-1],[-1,2,0,1],[-1,-2,0,-1],[2,1,1,0],[2,-1,1,0],[-2,1,-1,0],[-2,-1,-1,0]].forEach(function(e){x(b+e[0],h+e[1])&&0==p[b+e[2]][h+e[3]]&&a.push(new Move(b,h,b+e[0],h+e[1]))});return a}function n(b,h){var e=[];for(r=0;4>r;++r){var g,c;g=b+d[r];for(c=h+a[r];x(g,c)&&(e.push(new Move(b,h,g,c)),0==p[g][c]);g+=
d[r],c+=a[r]);}return e}function c(b,h){var e=[];for(r=0;4>r;++r){var g,c,t=!1;g=b+d[r];for(c=h+a[r];x(g,c);g+=d[r],c+=a[r])if(!t&&0==p[g][c])e.push(new Move(b,h,g,c));else if(!t&&0!=p[g][c])t=!0;else if(t&&0!=p[g][c]){e.push(new Move(b,h,g,c));break}}return e}function t(b,h){var a=[];4<b?a.push(new Move(b,h,b-1,h)):(x(b-1,h)&&a.push(new Move(b,h,b-1,h)),x(b,h-1)&&a.push(new Move(b,h,b,h-1)),x(b,h+1)&&a.push(new Move(b,h,b,h+1)));return a}function v(b,a){var e=[];4<b?(x(b+1,a)&&e.push(new Move(b,
a,b+1,a)),x(b,a-1)&&e.push(new Move(b,a,b,a-1)),x(b,a+1)&&e.push(new Move(b,a,b,a+1))):e.push(new Move(b,a,b+1,a));return e}function F(b,a,e){var g=l(p[b][a]),d=isRedPiece(p[b][a]),f=[];1==g?f=y(b,a):2==g?f=q(b,a):3==g?f=d?E(b,a):C(b,a):4==g?f=u(b,a):5==g?f=n(b,a):6==g?f=c(b,a):7==g&&(f=d?t(b,a):v(b,a));f.forEach(function(b){0!=p[b.i2][b.j2]&&isRedPiece(p[b.i2][b.j2])==d||e.push(b)})}function m(b){var a=[];for(i=0;10>i;++i)for(j=0;9>j;++j)0!=p[i][j]&&isRedPiece(p[i][j])==b&&F(i,j,a);return a}this.reset=
f;this.setMoves=function(b){var a=A;f();for(var e=!0,g=0,d=0;d<b.length;++d)B(b[d][0],b[d][1],b[d][2],b[d][3]),e&&a.length>d&&a[d].i1==b[d][0]&&a[d].j1==b[d][1]&&a[d].i2==b[d][2]&&a[d].j2==b[d][3]?++g:e=!1;return g};this.move=B;this.checkMove=function(b,a,e,d){var g=w();if(!m(g).find(function(g,c,f){return g.i1==b&&g.j1==a&&g.i2==e&&g.j2==d}))return!1;if(p[e][d]==(g?PIECE_BK:PIECE_RK))return!0;var c=!1;B(b,a,e,d);m(!g).find(function(b,a,e){return p[b.i2][b.j2]==(g?PIECE_RK:PIECE_BK)})&&(c=!0);D();
return!c};this.moveHistory=function(){for(var b=[],a=0;a<A.length;++a)b.push(A[a]);return b};this.pieceAt=function(b,a){return p[b][a]};this.isRedNext=w;this.numMoves=function(){return A.length};var p=[],A=[];f();var d=[0,1,0,-1],a=[1,0,-1,0],e=[1,1,-1,-1],g=[1,-1,-1,1]};function removeAllChildren(w){for(w=document.getElementById(w);w.lastChild;)w.removeChild(w.lastChild)}
function BoardUI(w){function l(){return document.getElementById("board")}function f(d,a){A&&(a=8-a);return m/2+a*m}function B(d,a){A&&(d=9-d);return 5>a?m/2+d*m:m/2+d*m+p}function D(d,a,e,g,b,h){var c=document.createElementNS(t,"line");c.setAttribute("x1",d);c.setAttribute("y1",a);c.setAttribute("x2",e);c.setAttribute("y2",g);c.setAttribute("class",b);h&&(c.id=h);return c}function x(d,a,e,g,b){var c=f(d,a);d=B(d,a);a=document.createElementNS(t,"circle");a.setAttribute("cx",c);a.setAttribute("cy",
d);a.setAttribute("r",e);a.setAttribute("class",g);b&&(a.id=b);return a}function z(d,a){return"abcdefghi"[a]+(9-d).toString()}function y(d,a){return function(){w(d,a)}}function q(d,a){var e=x(d,a,23,"piece-cover","piece-cover-"+z(d,a));e.style.strokeWidth=0;e.style.fillOpacity=0;e.userSelect="none";e.onmousedown=y(d,a);e.touchend=e.onmousedown;C(e)}function E(d,a){var e="piece-cover-"+z(d,a);null!=document.getElementById(e)&&u(e)}function C(d){l().appendChild(d)}function u(d){l().removeChild(document.getElementById(d))}
function n(d,a,e,g){var b;b=f(d,a);d=B(d,a);a=f(e,g);e=B(e,g);b=D(b,d,a,e,"grid",void 0);b.style.strokeWidth=1;b.style.stroke="gray";C(b)}function c(d){A=d;removeAllChildren("board");l();for(i=0;9>i;++i)n(0,i,4,i),0!=i&&8!=i||n(4,i,5,i),n(5,i,9,i);for(i=0;10>i;++i)n(i,0,i,8);n(0,3,2,5);n(0,5,2,3);n(7,3,9,5);n(9,3,7,5);for(i=0;10>i;++i)for(j=0;9>j;++j)q(i,j)}this.reset=c;this.drawPiece=function(d,a,e,g){E(d,a);var b=x(d,a,23,"piece-outer","piece-outer-"+z(d,a)),c=x(d,a,20,"piece-inner","piece-inner-"+
z(d,a));g=g?F[e]:v[e];var p="piece-text-"+z(d,a),l=f(d,a),n=B(d,a),m=document.createElementNS(t,"text");m.style.fontFamily="Roboto,monospace";m.style.fontSize=24;m.setAttribute("text-anchor","middle");m.setAttribute("alignment-baseline","central");m.setAttribute("x",l);m.setAttribute("y",n);m.appendChild(document.createTextNode(g));m.setAttribute("class","piece-text");m.userSelect="none";p&&(m.id=p);isRedPiece(e)?(b.setAttribute("stroke","red"),c.style.stroke="red",m.style.fill="red"):(b.style.stroke=
"black",c.style.stroke="black",m.style.fill="black");b.style.strokeWidth=2;c.style.strokeWidth=2;b.style.fill="white";c.style.fillOpacity=0;C(b);C(c);C(m);q(d,a)};this.erasePiece=function(d,a){E(d,a);u("piece-text-"+z(d,a));u("piece-inner-"+z(d,a));u("piece-outer-"+z(d,a));q(d,a)};this.highlightSquare=function(d,a){var e=f(d,a),g=B(d,a),b=m/6;for(d=-1;1>=d;d+=2){var c=D(e-23,g+23*d,e-23+b,g+23*d,"highlighter",void 0);c.style.strokeWidth=2;c.style.stroke="blue";C(c);c=D(e+23-b,g+23*d,e+23,g+23*d,"highlighter",
void 0);c.style.strokeWidth=2;c.style.stroke="blue";C(c)}for(d=-1;1>=d;d+=2)c=D(e+23*d,g-23,e+23*d,g-23+b,"highlighter",void 0),c.style.strokeWidth=2,c.style.stroke="blue",C(c),c=D(e+23*d,g+23-b,e+23*d,g+23,"highlighter",void 0),c.style.strokeWidth=2,c.style.stroke="blue",C(c)};this.eraseHighlights=function(){for(var c=l().getElementsByClassName("highlighter");0<c.length;)l().removeChild(c[0])};var t="http://www.w3.org/2000/svg",v=" \u5c07 \u58eb \u8c61 \u99ac \u8eca \u7832 \u5352  \u5e25 \u4ed5 \u76f8 \u508c \u4fe5 \u70ae \u5175".split(" "),
F=" \u5c07 \u58eb \u8c61 \ud83d\udc34 \u8eca \u7832 \u5352  \u5e25 \u4ed5 \u76f8 \ud83e\udd84 \u4fe5 \u70ae \u5175".split(" "),m=50,p=0,A=!1;c(!1)};function Board(w,l){function f(){for(var c=0;10>c;++c)for(var f=0;9>f;++f)y.pieceAt(c,f)!=PIECE_NONE&&q.drawPiece(c,f,y.pieceAt(c,f),!1);n=y.numMoves()}function B(c){c=Math.max(0,c);c=Math.min(y.numMoves(),c);if(c!=n){var f=y.moveHistory();if(c>n)for(var v=n;v<c;++v)x(f[v]);else for(v=n-1;v>=c;--v)0<v?z(f[v],f[v-1]):z(f[v],null);n=c}}function D(c){return c==PIECE_NONE?!1:"r"==E?isRedPiece(c):"b"==E?!isRedPiece(c):!1}function x(c){q.erasePiece(c.i1,c.j1);var f=!1;c.capture&&(q.erasePiece(c.i2,c.j2),
l&&(f=!0));q.drawPiece(c.i2,c.j2,c.piece,f);q.eraseHighlights();q.highlightSquare(c.i1,c.j1);q.highlightSquare(c.i2,c.j2);u=null}function z(c,f){q.drawPiece(c.i1,c.j1,c.piece,!1);q.erasePiece(c.i2,c.j2);c.capture&&q.drawPiece(c.i2,c.j2,c.capture,!1);q.eraseHighlights();f&&(q.highlightSquare(f.i1,f.j1),q.highlightSquare(f.i2,f.j2));u=null}this.setState=function(c,t,v){c!=E&&(E=c,q.reset("b"==c),y.reset(),f(),u=null);C=t;c=y.moveHistory();v=y.setMoves(v);t=n;n==c.length&&(t=y.numMoves());for(t=Math.min(t,
y.numMoves());n>v;--n){var l=n-1;0<l?z(c[l],c[l-1]):z(c[l],null)}B(t)};this.showMove=B;this.isRedNext=function(){return y.isRedNext()};this.numMoves=function(){return y.numMoves()};this.numMovesShown=function(){return n};var y=new Chess,q=new BoardUI(function(c,f){if(!C){var l=y.isRedNext();if(("r"==E&&l||"b"==E&&!l)&&n==y.numMoves())if(u)if(y.checkMove(u[0],u[1],c,f)){var l=u[0],z=u[1];x(y.move(l,z,c,f));++n;w(l,z,c,f)}else D(y.pieceAt(c,f))&&(q.eraseHighlights(),u=[c,f],q.highlightSquare(c,f));
else D(y.pieceAt(c,f))&&(q.eraseHighlights(),u=[c,f],q.highlightSquare(c,f))}}),E="r",C=!0,u=null,n=0;f()};String.prototype.endsWith||(String.prototype.endsWith=function(w,l){var f=this.toString();if(void 0===l||l>f.length)l=f.length;l-=w.length;f=f.indexOf(w,l);return-1!==f&&f===l});
function Game(w,l,f){function B(a,e,c,b,f,m,l){var n=new XMLHttpRequest;n.onreadystatechange=function(){if(4==n.readyState){var a=d.indexOf(c);if(-1!=a){d.splice(a,1);for(var b=p+1;b<=A;++b)if(a=d.indexOf(b),-1==a)p=b;else break;requestResolved=!0}else requestResolved=!1;200<=n.status&&299>=n.status?requestResolved||A==c?m(n.responseText):console.log("Dropped response from an old request."):l&&l(n.responseText)}};n.open(a,e,!0);b&&n.setRequestHeader("Content-type",b);f?n.send(f):n.send()}function D(a,
e,c,b){++A;d.push(A);B("POST",a,A,"application/x-www-form-urlencoded; charset=UTF-8",e,c,b)}function x(a){if("fail"==a)alert("Operation failed");else try{var c=JSON.parse(a);c.gameinfo&&("success"!==c.status&&console.log("last update failed"),c=c.gameinfo);f=c;F()}catch(d){console.log("Unrecognized server response: "+a)}}function z(a){a=a.split("/");for(var c=[],d=1;d<a.length;++d){var b=a[d];if("R"==b||"B"==b)break;c.push([parseInt(b[0],10),parseInt(b[1],10),parseInt(b[2],10),parseInt(b[3],10)])}return c}
function y(a,e,d,b){var h=f;a=[a,e,d,b];h.moves+="/"+(""+a[0]+a[1]+a[2]+a[3]);c();D("/gameinfo","uid="+l+"&sid="+E("sid")+"&gid="+w+"&moves="+f.moves,x,q);v()}function q(a){console.log("Retrieve game info failed")}function E(a){a+="=";for(var c=document.cookie.split(";"),d=0;d<c.length;++d){for(var b=c[d];" "==b.charAt(0);)b=b.substring(1);if(0==b.indexOf(a))return b.substring(a.length,b.length)}return""}function C(a){var c=document.getElementById(a+"-player"),d=document.getElementById(a+"-sit-link");
c.removeChild(d);c.appendChild(document.createTextNode("sitting down..."));D("/gameinfo","uid="+l+"&sid="+E("sid")+"&gid="+w+"&sit="+a,x,q)}function u(a,c,d,b,f){var l=document.createElement("a");l.id=a;c&&(l.className=c);l.href=d;b&&(l.onclick=b);l.appendChild(document.createTextNode(f));return l}function n(){removeAllChildren("red-player");removeAllChildren("black-player");if(void 0!==f.red&&null!==f.red){var a="";f.red.id==l&&(a=" (you)");document.getElementById("red-player").appendChild(document.createTextNode("Red: "+
f.red.name+a))}else document.getElementById("red-player").appendChild(document.createTextNode("Red: ")),a=u("red-sit-link",void 0,"#",function(){C("red");return!1},"sit here"),document.getElementById("red-player").appendChild(a);void 0!==f.black&&null!==f.black?(a="",f.black.id==l&&(a=" (you)"),document.getElementById("black-player").appendChild(document.createTextNode("Black: "+f.black.name+a))):(document.getElementById("black-player").appendChild(document.createTextNode("Black: ")),a=u("black-sit-link",
void 0,"#",function(){C("black");return!1},"sit here"),document.getElementById("black-player").appendChild(a))}function c(){removeAllChildren("status");var a=document.getElementById("status");f.moves.endsWith("R")?a.appendChild(document.createTextNode("Red won")):f.moves.endsWith("B")?a.appendChild(document.createTextNode("Black won")):f.red&&f.black?m.isRedNext()?a.appendChild(document.createTextNode("Red to go")):a.appendChild(document.createTextNode("Black to go")):a.appendChild(document.createTextNode("Waiting for players to join..."))}
function t(a,c){var d=document.createElement("td");d.appendChild(c);a.appendChild(d)}function v(){removeAllChildren("move-history");var a=document.getElementById("move-history"),c=document.createElement("table");c.id="moveHistoryControls";var d=document.createElement("tr");c.appendChild(d);0<m.numMovesShown()?(t(d,u("move-history-first",void 0,"#",function(){m.showMove(0);v();return!1},"first")),t(d,u("move-history-prev",void 0,"#",function(){m.showMove(m.numMovesShown()-1);v();return!1},"prev"))):
(t(d,document.createTextNode("first")),t(d,document.createTextNode("prev")));t(d,document.createTextNode(""+m.numMovesShown()+" / "+m.numMoves()));m.numMovesShown()<m.numMoves()?(t(d,u("move-history-next",void 0,"#",function(){m.showMove(m.numMovesShown()+1);v();return!1},"next")),t(d,u("move-history-last",void 0,"#",function(){m.showMove(m.numMoves());v();return!1},"last"))):(t(d,document.createTextNode("next")),t(d,document.createTextNode("last")));a.appendChild(c);c=document.createElement("div");
c.id="moveHistoryFork";c.appendChild(u("move-history-fork-link",void 0,"/fork/"+w+"/"+m.numMovesShown().toString(),void 0,"fork"));c.appendChild(document.createTextNode(" this game from here"));a.appendChild(c)}function F(){n();var a="r";f.black&&f.black.id==l&&(a="b");var d=f.black&&f.black.id==l||f.red&&f.red.id==l;m.setState(a,!(f.red&&f.black&&!f.moves.endsWith("R")&&!f.moves.endsWith("B"))||!d,z(f.moves));c();v()}var m,p=0,A=0,d=[];(function(){m=new Board(y,!1);F();window.setInterval(function(){B("GET",
"/gameinfo?gid="+w,p,void 0,void 0,x,q)},1E3)})()}document.onreadystatechange=function(){"interactive"==document.readyState&&new Game(currentGameId,myUid,gameInfo)};
