application: zaixianxiangqi
version: 2
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css

- url: /.*
  script: xiangqi.app
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]
