runtime: go116

main: ./cmd/zaixianxiangqi

handlers:
- url: /css
  secure: always
  static_dir: web/css

- url: /js
  secure: always
  static_dir: web/js

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
