function parseMoves(a){a=a.split("/");for(var b=[],c=1;c<a.length;++c){var d=a[c];if("R"==d||"B"==d||"D"==d)break;b.push([parseInt(d[0],10),parseInt(d[1],10),parseInt(d[2],10),parseInt(d[3],10)])}return b}function removeAllChildren(a){for(a=document.getElementById(a);a.lastChild;)a.removeChild(a.lastChild)}
function createLink(a,b,c,d,m){var l=document.createElement("a");a&&(l.id=a);b.forEach(function(b){l.classList.add(b)});l.href=c;d&&(l.onclick=d);l.appendChild(document.createTextNode(m));return l}String.prototype.endsWith||(String.prototype.endsWith=function(a,b){var c=this.toString();if(void 0===b||b>c.length)b=c.length;b-=a.length;c=c.indexOf(a,b);return-1!==c&&c===b});
function ajax(a,b,c,d,m,l){var g=new XMLHttpRequest;g.onreadystatechange=function(){4==g.readyState&&(200<=g.status&&299>=g.status?m(g.responseText):l(g.responseText))};g.open(a,b,!0);c&&g.setRequestHeader("Content-type",c);d?g.send(d):g.send()}function ajaxGet(a,b,c){ajax("GET",a,void 0,void 0,b,c)}function ajaxPost(a,b,c,d){ajax("POST",a,"application/x-www-form-urlencoded; charset=UTF-8",b,c,d)}
function enableLink(a,b){var c=document.getElementById(a);b?c.classList.remove("disabled"):c.classList.add("disabled")}function getCookie(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;++c){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return""}function getSid(){return getCookie("sid")}function setSpanText(a,b){removeAllChildren(a);document.getElementById(a).appendChild(document.createTextNode(b))};var PIECE_NONE=0,PIECE_K=1,PIECE_A=2,PIECE_E=3,PIECE_H=4,PIECE_R=5,PIECE_C=6,PIECE_P=7,PIECE_BK=1,PIECE_BA=2,PIECE_BE=3,PIECE_BH=4,PIECE_BR=5,PIECE_BC=6,PIECE_BP=7,PIECE_RK=9,PIECE_RA=10,PIECE_RE=11,PIECE_RH=12,PIECE_RR=13,PIECE_RC=14,PIECE_RP=15;function isRedPiece(a){return 8<=a}function Move(a,b,c,d,m,l){this.i1=a;this.j1=b;this.i2=c;this.j2=d;this.piece=m||PIECE_NONE;this.capture=l||PIECE_NONE}
function Chess(){function a(){return 0==r.length%2}function b(v){return 8<=v?v-8:v}function c(){k=[];r=[];for(var v=0;10>v;++v){k.push([]);for(var b=0;9>b;++b)k[v].push(0)}v="rheakaehr 9 1c5c1 p1p1p1p1p 9 9 P1P1P1P1P 1C5C1 9 RHEAKAEHR".split(" ");if(10!=v.length)throw"Malformed fen string: rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";for(b=0;10>b;++b)for(var a=0,e=0;e<v[b].length;++e){if(9<=a)throw"Malformed fen string at row "+b+": rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";
var c=v[b][e];if("0"<=c&&"9">=c)a+=parseInt(v[b][e],10);else{var c=k[b],f=a,h=v[b][e],u=h==h.toLowerCase(),h=h.toLowerCase(),d=0;"k"==h?d=1:"a"==h?d=2:"e"==h?d=3:"h"==h?d=4:"r"==h?d=5:"c"==h?d=6:"p"==h&&(d=7);u||(d+=8);c[f]=d;++a}}}function d(b,a,c,e){r.push(new Move(b,a,c,e,k[b][a],k[c][e]));k[c][e]=k[b][a];k[b][a]=0;return r[r.length-1]}function m(){var b=r.pop();k[b.i1][b.j1]=k[b.i2][b.j2];k[b.i2][b.j2]=b.capture}function l(b,a){return 0<=b&&10>b&&0<=a&&9>a}function g(b,a){return 3<=a&&5>=a&&(0<=
b&&2>=b||7<=b&&9>=b)}function f(a,B){for(var c=[],e=0;4>e;++e)g(a+y[e],B+u[e])&&c.push(new Move(a,B,a+y[e],B+u[e]));for(e=-1;1>=e;e+=2)for(var h=a+e;0<=h&&10>h&&(b(k[h][B])==PIECE_K&&c.push(new Move(a,B,h,B)),0==k[h][B]);h+=e);return c}function w(b,a){for(var c=[],e=0;4>e;++e)g(b+A[e],a+q[e])&&c.push(new Move(b,a,b+A[e],a+q[e]));return c}function z(b,a){for(var c=[],e=0;4>e;++e)l(b+2*A[e],a+2*q[e])&&0==k[b+A[e]][a+q[e]]&&4<b+A[e]&&c.push(new Move(b,a,b+2*A[e],a+2*q[e]));return c}function t(b,a){for(var c=
[],e=0;4>e;++e)!l(b+2*A[e],a+2*q[e])||0!=k[b+A[e]][a+q[e]]||4<b+A[e]||c.push(new Move(b,a,b+2*A[e],a+2*q[e]));return c}function n(b,a){var c=[];[[1,2,0,1],[1,-2,0,-1],[-1,2,0,1],[-1,-2,0,-1],[2,1,1,0],[2,-1,1,0],[-2,1,-1,0],[-2,-1,-1,0]].forEach(function(e){l(b+e[0],a+e[1])&&0==k[b+e[2]][a+e[3]]&&c.push(new Move(b,a,b+e[0],a+e[1]))});return c}function h(b,a){for(var c=[],e=0;4>e;++e){var h,f;h=b+y[e];for(f=a+u[e];l(h,f)&&(c.push(new Move(b,a,h,f)),0==k[h][f]);h+=y[e],f+=u[e]);}return c}function p(b,
a){for(var c=[],e=0;4>e;++e){var h,f,d=!1;h=b+y[e];for(f=a+u[e];l(h,f);h+=y[e],f+=u[e])if(!d&&0==k[h][f])c.push(new Move(b,a,h,f));else if(!d&&0!=k[h][f])d=!0;else if(d&&0!=k[h][f]){c.push(new Move(b,a,h,f));break}}return c}function D(b,a){var c=[];4<b?c.push(new Move(b,a,b-1,a)):(l(b-1,a)&&c.push(new Move(b,a,b-1,a)),l(b,a-1)&&c.push(new Move(b,a,b,a-1)),l(b,a+1)&&c.push(new Move(b,a,b,a+1)));return c}function x(b,a){var c=[];4<b?(l(b+1,a)&&c.push(new Move(b,a,b+1,a)),l(b,a-1)&&c.push(new Move(b,
a,b,a-1)),l(b,a+1)&&c.push(new Move(b,a,b,a+1))):c.push(new Move(b,a,b+1,a));return c}function C(a,c,d){var e=b(k[a][c]),u=isRedPiece(k[a][c]),q=[];1==e?q=f(a,c):2==e?q=w(a,c):3==e?q=u?z(a,c):t(a,c):4==e?q=n(a,c):5==e?q=h(a,c):6==e?q=p(a,c):7==e&&(q=u?D(a,c):x(a,c));q.forEach(function(b){0!=k[b.i2][b.j2]&&isRedPiece(k[b.i2][b.j2])==u||d.push(b)})}function E(b){for(var a=[],c=0;10>c;++c)for(var e=0;9>e;++e)0!=k[c][e]&&isRedPiece(k[c][e])==b&&C(c,e,a);return a}this.reset=c;this.setMoves=function(b){var a=
r;c();for(var h=!0,e=0,f=0;f<b.length;++f)d(b[f][0],b[f][1],b[f][2],b[f][3]),h&&a.length>f&&a[f].i1==b[f][0]&&a[f].j1==b[f][1]&&a[f].i2==b[f][2]&&a[f].j2==b[f][3]?++e:h=!1;return e};this.move=d;this.checkMove=function(b,c,f,e){var h=a();if(!E(h).find(function(a,h,d){return a.i1==b&&a.j1==c&&a.i2==f&&a.j2==e}))return!1;if(k[f][e]==(h?PIECE_BK:PIECE_RK))return!0;var u=!1;d(b,c,f,e);E(!h).find(function(b,a,c){return k[b.i2][b.j2]==(h?PIECE_RK:PIECE_BK)})&&(u=!0);m();return!u};this.moveHistory=function(){for(var b=
[],a=0;a<r.length;++a)b.push(r[a]);return b};this.moveHistoryArrayFormat=function(){for(var b=[],a=0;a<r.length;++a){var c=r[a];b.push([c.i1,c.j1,c.i2,c.j2])}return b};this.lastMove=function(){return r[r.length-1]};this.pieceAt=function(b,a){return k[b][a]};this.isRedNext=a;this.numMoves=function(){return r.length};this.getFen=function(){for(var b="",c=0;10>c;++c){for(var f=0;9>f;++f)if(""==k[c][f]){for(var e=f+1;9>e&&""==k[c][e];)++e;b+=""+(e-f);f=e-1}else{var e=k[c][f],h=isRedPiece(e);h&&(e-=8);
var d="";1==e?d="K":2==e?d="A":3==e?d="E":4==e?d="H":5==e?d="R":6==e?d="C":7==e&&(d="P");h||(d=d.toLowerCase());b+=d}9>c&&(b+="/")}return b+=" "+(a()?"w":"b")};var k=[],r=[];c();var y=[0,1,0,-1],u=[1,0,-1,0],A=[1,1,-1,-1],q=[1,-1,-1,1]};function BoardUI(a){function b(){return document.getElementById("board")}function c(b,a){y&&(a=8-a);return k/2+a*k}function d(b,a){y&&(b=9-b);return 5>a?k/2+b*k:k/2+b*k+r}function m(b,a,c,f,h,d){var e=document.createElementNS(C,"line");e.setAttribute("x1",b);e.setAttribute("y1",a);e.setAttribute("x2",c);e.setAttribute("y2",f);e.classList.add(h);d&&(e.id=d);return e}function l(b,a,f,h,g){var p=c(b,a);a=d(b,a);var e=document.createElementNS(C,"circle");e.setAttribute("cx",p);e.setAttribute("cy",a);
e.setAttribute("r",f);e.classList.add(h[b]);e.classList.add("piece-element");g&&(e.id=g);return e}function g(b,a){return"abcdefghi"[a]+(9-b).toString()}function f(b,a,f,h,p){p&&t(a,f);var k=void 0;p&&(k="piece-outer-"+g(a,f));var k=l(a,f,23,"piece-outer",k),e=void 0;p&&(e="piece-inner-"+g(a,f));var e=l(a,f,20,"piece-inner",e),w=E[h],m=void 0;p&&(m="piece-text-"+g(a,f));p=m;m=c(a,f);a=d(a,f);f=document.createElementNS(C,"text");f.style.fontFamily="Roboto,monospace";f.style.fontSize="24px";f.setAttribute("text-anchor",
"middle");f.setAttribute("alignment-baseline","central");f.setAttribute("dominant-baseline","middle");f.setAttribute("font-weight","bold");f.setAttribute("x",m);f.setAttribute("y",a);f.appendChild(document.createTextNode(w));f.classList.add("piece-text");f.classList.add("piece-element");f.userSelect="none";p&&(f.id=p);isRedPiece(h)?(k.setAttribute("stroke","red"),e.style.stroke="red",f.style.fill="red"):(k.style.stroke="black",e.style.stroke="black",f.style.fill="black");k.style.strokeWidth=2;e.style.strokeWidth=
2;k.style.fill="white";e.style.fillOpacity=0;b.appendChild(k);b.appendChild(e);b.appendChild(f)}function w(b,c){return function(){a(b,c)}}function z(b,a){var c=l(b,a,23,"piece-cover","piece-cover-"+g(b,a));c.style.strokeWidth=0;c.style.fillOpacity=0;c.userSelect="none";c.onmousedown=w(b,a);c.touchend=c.onmousedown;n(c)}function t(b,a){var c="piece-cover-"+g(b,a);null!=document.getElementById(c)&&h(c)}function n(a){b().appendChild(a)}function h(a){b().removeChild(document.getElementById(a))}function p(b,
a,f,h){var p;p=c(b,a);b=d(b,a);a=c(f,h);f=d(f,h);p=m(p,b,a,f,"grid",void 0);p.style.strokeWidth=1;p.style.stroke="gray";n(p)}function D(){for(i=0;9>i;++i)p(0,i,4,i),0!=i&&8!=i||p(4,i,5,i),p(5,i,9,i);for(i=0;10>i;++i)p(i,0,i,8);p(0,3,2,5);p(0,5,2,3);p(7,3,9,5);p(9,3,7,5);for(i=0;10>i;++i)for(j=0;9>j;++j)z(i,j)}function x(){for(var a=b().getElementsByClassName("highlighter");0<a.length;)b().removeChild(a[0])}this.reset=function(a){if(y==a){for(a=b().getElementsByClassName("piece-element");0<a.length;)b().removeChild(a[0]);
x()}else y=a,removeAllChildren("board"),D()};this.drawPieceWithCover=function(a,c,h){f(b(),a,c,h,!0);z(a,c)};this.erasePiece=function(a,b){t(a,b);h("piece-text-"+g(a,b));h("piece-inner-"+g(a,b));h("piece-outer-"+g(a,b));z(a,b)};this.drawColorIndicator=function(a,b){var c=1;b&&(c+=8);f(a,0,0,c,!1)};this.highlightSquare=function(a,b){var f=c(a,b),h=d(a,b),p=k/6;for(a=-1;1>=a;a+=2){var g=m(f-23,h+23*a,f-23+p,h+23*a,"highlighter",void 0);g.style.strokeWidth=2;g.style.stroke="blue";n(g);g=m(f+23-p,h+23*
a,f+23,h+23*a,"highlighter",void 0);g.style.strokeWidth=2;g.style.stroke="blue";n(g)}for(a=-1;1>=a;a+=2)g=m(f+23*a,h-23,f+23*a,h-23+p,"highlighter",void 0),g.style.strokeWidth=2,g.style.stroke="blue",n(g),g=m(f+23*a,h+23-p,f+23*a,h+23,"highlighter",void 0),g.style.strokeWidth=2,g.style.stroke="blue",n(g)};this.eraseHighlights=x;var C="http://www.w3.org/2000/svg",E=" \u5c07 \u58eb \u8c61 \u99ac \u8eca \u7832 \u5352  \u5e25 \u4ed5 \u76f8 \u508c \u4fe5 \u70ae \u5175".split(" "),k=50,r=0,y=!1;D()};function Board(a){function b(){for(var a=0;10>a;++a)for(var b=0;9>b;++b)g.pieceAt(a,b)!=PIECE_NONE&&f.drawPieceWithCover(a,b,g.pieceAt(a,b));n=g.numMoves()}function c(a){a=Math.max(0,a);a=Math.min(g.numMoves(),a);if(a==n)return n;var b=g.moveHistory();if(a>n)for(var c=n;c<a;++c)m(b[c]);else for(c=n-1;c>=a;--c)0<c?l(b[c],b[c-1]):l(b[c],null);return n=a}function d(a){return a==PIECE_NONE?!1:"r"==w?isRedPiece(a):"b"==w?!isRedPiece(a):!1}function m(a){f.erasePiece(a.i1,a.j1);a.capture&&f.erasePiece(a.i2,
a.j2);f.drawPieceWithCover(a.i2,a.j2,a.piece);f.eraseHighlights();f.highlightSquare(a.i1,a.j1);f.highlightSquare(a.i2,a.j2);t=null}function l(a,b){f.drawPieceWithCover(a.i1,a.j1,a.piece);f.erasePiece(a.i2,a.j2);a.capture&&f.drawPieceWithCover(a.i2,a.j2,a.capture);f.eraseHighlights();b&&(f.highlightSquare(b.i1,b.j1),f.highlightSquare(b.i2,b.j2));t=null}this.setState=function(a,d,m){a!=w&&(w=a,f.reset("b"==a),g.reset(),b(),t=null);z=d;a=g.moveHistory();m=g.setMoves(m);d=n;n==a.length&&(d=g.numMoves());
for(d=Math.min(d,g.numMoves());n>m;--n){var x=n-1;0<x?l(a[x],a[x-1]):l(a[x],null)}c(d)};this.resetState=function(a,c,d){w=a;f.reset("b"==a);g.reset();g.setMoves(d);b();t=null;n=g.numMoves();0<g.numMoves()&&(a=g.lastMove(),f.highlightSquare(a.i1,a.j1),f.highlightSquare(a.i2,a.j2))};this.showMove=c;this.isRedNext=function(){return g.isRedNext()};this.numMoves=function(){return g.numMoves()};this.numMovesShown=function(){return n};this.getFen=function(){for(var a=g.moveHistoryArrayFormat(),b=[],c=0;c<
n;++c)b.push(a[c]);g.setMoves(b);b=g.getFen();g.setMoves(a);return b};var g=new Chess,f=new BoardUI(function(b,c){if(!z){var l=g.isRedNext();if(("r"==w&&l||"b"==w&&!l)&&n==g.numMoves())if(t)if(g.checkMove(t[0],t[1],b,c)){var l=t[0],x=t[1];m(g.move(l,x,b,c));++n;a(l,x,b,c)}else d(g.pieceAt(b,c))&&(f.eraseHighlights(),t=[b,c],f.highlightSquare(b,c));else d(g.pieceAt(b,c))&&(f.eraseHighlights(),t=[b,c],f.highlightSquare(b,c))}}),w="r",z=!0,t=null,n=0;f.drawColorIndicator(document.getElementById("redIndicator"),
!0);f.drawColorIndicator(document.getElementById("blackIndicator"),!1);b()};function Stopwatch(a){function b(){return document.getElementById(a)}function c(){if(l){var b=document.getElementById(a+"Hand"),c=.8*m,z=g/d*2*Math.PI;b.setAttribute("x2",c*Math.sin(z));b.setAttribute("y2",-c*Math.cos(z));++g;g%=d}}this.start=function(){l||(l=!0,g=0,c(),b().style.visibility="visible")};this.stop=function(){l=!1;b().style.visibility="hidden"};this.tick=c;this.frequency=function(){return d};var d=60,m=20,l=!1,g=0;(function(){var c=document.createElementNS("http://www.w3.org/2000/svg",
"circle");c.setAttribute("cx",0);c.setAttribute("cy",0);c.setAttribute("r",m);c.style.stroke="black";c.style.strokeWidth=2;c.style.fillOpacity=0;b().appendChild(c);c=document.createElementNS("http://www.w3.org/2000/svg","line");c.setAttribute("x1",0);c.setAttribute("y1",-m);c.setAttribute("x2",0);c.setAttribute("y2",-m-6);c.style.strokeWidth=4;c.style.stroke="black";b().appendChild(c);c=document.createElementNS("http://www.w3.org/2000/svg","rect");c.setAttribute("x",-3);c.setAttribute("y",-m-6-4);
c.setAttribute("width",6);c.setAttribute("height",4);c.style.strokeWidth=.5;c.style.stroke="black";c.style.fillOpacity=0;b().appendChild(c);c=document.createElementNS("http://www.w3.org/2000/svg","circle");c.setAttribute("cx",0);c.setAttribute("cy",-m-6-2);c.setAttribute("r",6);c.style.stroke="black";c.style.strokeWidth=1;c.style.fillOpacity=0;b().appendChild(c);for(c=-3;3>=c;c+=1){var d=document.createElementNS("http://www.w3.org/2000/svg","line");d.setAttribute("x1",c);d.setAttribute("y1",-m-6-
4);d.setAttribute("x2",c);d.setAttribute("y2",-m-6);d.style.strokeWidth=.2;d.style.stroke="black";b().appendChild(d)}for(c=0;12>c;++c){var d=document.createElementNS("http://www.w3.org/2000/svg","line"),g=c/12*2*Math.PI,l=m,n=.7*m;d.setAttribute("x1",l*Math.sin(g));d.setAttribute("y1",-l*Math.cos(g));d.setAttribute("x2",n*Math.sin(g));d.setAttribute("y2",-n*Math.cos(g));d.style.strokeWidth=1;d.style.stroke="black";b().appendChild(d)}for(c=0;60>c;++c)d=document.createElementNS("http://www.w3.org/2000/svg",
"line"),g=c/60*2*Math.PI,l=m,n=.85*m,d.setAttribute("x1",l*Math.sin(g)),d.setAttribute("y1",-l*Math.cos(g)),d.setAttribute("x2",n*Math.sin(g)),d.setAttribute("y2",-n*Math.cos(g)),d.style.strokeWidth=.5,d.style.stroke="black",b().appendChild(d);c=document.createElementNS("http://www.w3.org/2000/svg","line");c.id=a+"Hand";c.setAttribute("x1",0);c.setAttribute("y1",0);c.setAttribute("x2",0);c.setAttribute("y2",.8*-m);c.style.strokeWidth=1.5;c.style.stroke="black";b().appendChild(c);b().style.visibility=
"hidden"})()};function createMenuToggleSpan(a){var b=document.createElement("span");b.classList.add("menu-toggle");a?b.appendChild(document.createTextNode("[+]")):b.appendChild(document.createTextNode("[-]"));return b}function toggleMenu(){var a=document.getElementById("menu-text"),b=document.getElementById("menu-content");"grid"==b.style.display?(b.style.display="none",a.innerHTML=createMenuToggleSpan(!0).outerHTML):(b.style.display="grid",a.innerHTML=createMenuToggleSpan(!1).outerHTML)}
var NavBarOptions=function(a,b){this.playerId=a;this.playerName=b;this.titleElementHTML="\u5728\u7ebf\u8c61\u68cb\u5bf9\u6218";this.menuFork=this.menuInviteAI=!1};function createNavBarUsernameElement(a,b){var c=document.createElement("div");c.appendChild(document.createTextNode("Hello, "+b));c.appendChild(document.createTextNode("!"));return c}function createNavBarTitleElement(a){var b=document.createElement("div");b.classList.add("nav-bar-middle");b.innerHTML=a;return b}
function createNavBarMenu(a){var b=document.createElement("div");b.classList.add("menu");var c=document.createElement("div");c.id="menu-text";c.onclick=toggleMenu;c.appendChild(createMenuToggleSpan(!0));b.appendChild(c);c=document.createElement("div");c.id="menu-content";c.classList.add("menu-content");var d=document.createElement("div");d.appendChild(createLink(null,[],"/new",null,"new game"));c.appendChild(d);a.menuInviteAI&&(d=document.createElement("div"),d.id="invite-ai-container",c.appendChild(d));
a.menuFork&&(d=document.createElement("div"),d.id="forkGame",c.appendChild(d));d=document.createElement("div");d.appendChild(createLink(null,[],"/user/"+a.playerId,null,"my profile"));c.appendChild(d);a=document.createElement("div");a.id="update-profile";a.appendChild(createLink(null,[],"/update_profile",null,"update profile"));c.appendChild(a);b.appendChild(c);return b}
function createNavBarRightElement(a){var b=document.createElement("div");b.classList.add("nav-bar-right");b.appendChild(createNavBarUsernameElement(a.playerId,a.playerName));b.appendChild(createNavBarMenu(a));return b}function createNavBarHomeElement(){var a=document.createElement("div");a.classList.add("nav-bar-left");a.appendChild(createLink(null,[],"/",null,"Home"));return a}
function initializeNavBar(a){var b=document.getElementById("nav");b.appendChild(createNavBarHomeElement());b.appendChild(createNavBarTitleElement(a.titleElementHTML));b.appendChild(createNavBarRightElement(a))};var Game=function(a,b,c,d){this.currentGameId_=a;this.myUid_=b;this.myName_=c;this.gameInfo_=d;this.ajaxSequenceHWM_=this.ajaxSequenceLWM_=0;this.pendingSequences_=[];this.initApplication()};Game.prototype.addPendingRequest=function(){++this.ajaxSequenceHWM_;this.pendingSequences_.push(this.ajaxSequenceHWM_);return this.ajaxSequenceHWM_};
Game.prototype.resolveRequest=function(a){a=this.pendingSequences_.indexOf(a);if(-1!=a){this.pendingSequences_.splice(a,1);for(var b=this.ajaxSequenceLWM_+1;b<=this.ajaxSequenceHWM_;++b)if(a=this.pendingSequences_.indexOf(b),-1==a)this.ajaxSequenceLWM_=b;else break;return!0}return!1};
Game.prototype.successWrapper=function(a,b,c){(requestResolved=this.resolveRequest(a))||this.ajaxSequenceHWM_==a?b(c):console.log("Dropped response from an old request: sequence "+a+", lwm "+this.ajaxSequenceLWM_+", hwm "+this.ajaxSequenceHWM_,NaN+this.pendingSequences_.join(", ")+"]")};Game.prototype.failureWrapper=function(a,b,c){this.resolveRequest(a);b(c)};
Game.prototype.get=function(a,b,c){var d=this.ajaxSequenceLWM_;ajaxGet(a,this.successWrapper.bind(this,d,b),this.failureWrapper.bind(this,d,c))};Game.prototype.post=function(a,b,c,d){var m=this.addPendingRequest();ajaxPost(a,b,this.successWrapper.bind(this,m,c),this.failureWrapper.bind(this,m,d))};
Game.prototype.onGameInfoUpdate=function(a){if("fail"==a)alert("Operation failed");else try{var b=JSON.parse(a);b.gameinfo&&("success"!==b.status&&console.log("last update failed"),b=b.gameinfo);this.gameInfo_=b;this.refreshGame()}catch(c){console.log("Unrecognized server response: "+a+". Error: "+c)}};
Game.prototype.parseMoves=function(a){a=a.split("/");for(var b=[],c=1;c<a.length;++c){var d=a[c];if("R"==d||"B"==d)break;b.push([parseInt(d[0],10),parseInt(d[1],10),parseInt(d[2],10),parseInt(d[3],10)])}return b};Game.prototype.moveToString=function(a){return""+a[0]+a[1]+a[2]+a[3]};
Game.prototype.onPlayerMove=function(a,b,c,d){this.gameInfo_.moves+="/"+this.moveToString([a,b,c,d]);this.updateStatus();this.post("/gameinfo","uid="+this.myUid_+"&sid="+getSid()+"&gid="+this.currentGameId_+"&moves="+this.gameInfo_.moves,this.onGameInfoUpdate.bind(this),this.onGameInfoUpdateFailure.bind(this));this.refreshMoveHistoryControls()};Game.prototype.onGameInfoUpdateFailure=function(a){console.log("Retrieve game info failed")};
Game.prototype.requestGameInfo=function(a){this.get("/gameinfo?gid="+a,this.onGameInfoUpdate.bind(this),this.onGameInfoUpdateFailure.bind(this))};Game.prototype.createInviteAILink=function(a){removeAllChildren("invite-ai-container");var b=createLink("invite-ai-link",[],"#",function(){this.inviteAI();return!1}.bind(this),"invite Blur");document.getElementById("invite-ai-container").appendChild(b);a||enableLink("invite-ai-link",!1)};
Game.prototype.sit=function(a){enableLink(a+"-sit-link",!1);this.post("/gameinfo","uid="+this.myUid_+"&sid="+getSid()+"&gid="+this.currentGameId_+"&sit="+a,this.onGameInfoUpdate.bind(this),this.onGameInfoUpdateFailure.bind(this))};Game.prototype.inviteAI=function(){enableLink("invite-ai-link",!1);this.post("/invite_ai","uid="+this.myUid_+"&sid="+getSid()+"&gid="+this.currentGameId_,this.onGameInfoUpdate.bind(this),this.onGameInfoUpdateFailure.bind(this))};
Game.prototype.createHintYou=function(a){var b=document.createElement("sup");b.className="hint-you";a?b.appendChild(document.createTextNode(" ")):b.appendChild(document.createTextNode("you"));return b};
Game.prototype.refreshPlayerList=function(){removeAllChildren("red-player");removeAllChildren("black-player");if(void 0!==this.gameInfo_.red&&null!==this.gameInfo_.red){var a=document.getElementById("red-player"),b=document.createElement("span");b.appendChild(createLink("red-player-link",["player-link"],"/user/"+this.gameInfo_.red.id,void 0,this.gameInfo_.red.name));a.appendChild(b);a.appendChild(this.createHintYou(this.gameInfo_.red.id!=this.myUid_))}else b=createLink("red-sit-link",["sit-link"],
"#",function(){this.sit("red");return!1}.bind(this),"sit here"),document.getElementById("red-player").appendChild(b);void 0!==this.gameInfo_.black&&null!==this.gameInfo_.black?(a=document.getElementById("black-player"),b=document.createElement("span"),b.appendChild(createLink("black-player-link",["player-link"],"/user/"+this.gameInfo_.black.id,void 0,this.gameInfo_.black.name)),a.appendChild(b),a.appendChild(this.createHintYou(this.gameInfo_.black.id!=this.myUid_))):(b=createLink("black-sit-link",
["sit-link"],"#",function(){this.sit("black");return!1}.bind(this),"sit here"),document.getElementById("black-player").appendChild(b))};Game.prototype.gameStarted=function(){return this.gameInfo_.red&&this.gameInfo_.black};
Game.prototype.updateStatus=function(){var a=document.getElementById("waitingStatus"),b=document.getElementById("playingStatus"),c=document.getElementById("redWonStatus"),d=document.getElementById("blackWonStatus");a.style.display="none";b.style.display="none";c.style.display="none";d.style.display="none";this.gameInfo_.moves.endsWith("R")?(c.style.display="inline-block",this.redWatch_.stop(),this.blackWatch_.stop()):this.gameInfo_.moves.endsWith("B")?(d.style.display="inline-block",this.redWatch_.stop(),
this.blackWatch_.stop()):this.gameStarted()?(b.style.display="inline-block",this.board_.isRedNext()?(this.redWatch_.start(),this.blackWatch_.stop()):(this.blackWatch_.start(),this.redWatch_.stop())):a.style.display="inline-block"};Game.prototype.gameInProgress=function(){return this.gameStarted()&&!this.gameInfo_.moves.endsWith("R")&&!this.gameInfo_.moves.endsWith("B")};Game.prototype.appendCellToRow=function(a,b){var c=document.createElement("td");c.appendChild(b);a.appendChild(c)};
Game.prototype.refreshMoveHistoryControls=function(){removeAllChildren("move-history");var a=document.getElementById("move-history"),b=document.createElement("table");b.id="moveHistoryControls";var c=document.createElement("tr");b.appendChild(c);0<this.board_.numMovesShown()?(this.appendCellToRow(c,createLink("move-history-first",[],"#",function(){this.board_.showMove(0);this.refreshMoveHistoryControls();return!1}.bind(this),"first")),this.appendCellToRow(c,createLink("move-history-prev",[],"#",function(){this.board_.showMove(this.board_.numMovesShown()-
1);this.refreshMoveHistoryControls();return!1}.bind(this),"prev"))):(this.appendCellToRow(c,document.createTextNode("first")),this.appendCellToRow(c,document.createTextNode("prev")));this.appendCellToRow(c,document.createTextNode(""+this.board_.numMovesShown()+" / "+this.board_.numMoves()));this.board_.numMovesShown()<this.board_.numMoves()?(this.appendCellToRow(c,createLink("move-history-next",[],"#",function(){this.board_.showMove(this.board_.numMovesShown()+1);this.refreshMoveHistoryControls();
return!1}.bind(this),"next")),this.appendCellToRow(c,createLink("move-history-last",[],"#",function(){this.board_.showMove(this.board_.numMoves());this.refreshMoveHistoryControls();return!1}.bind(this),"last"))):(this.appendCellToRow(c,document.createTextNode("next")),this.appendCellToRow(c,document.createTextNode("last")));a.appendChild(b);document.getElementById("forkGame");removeAllChildren("forkGame");forkGame.appendChild(createLink("move-history-fork-link",[],"/fork/"+this.currentGameId_+"/"+
this.board_.numMovesShown().toString(),void 0,"fork at move "+this.board_.numMovesShown()))};
Game.prototype.refreshGame=function(){this.refreshPlayerList();var a="r";this.gameInfo_.black&&this.gameInfo_.black.id==this.myUid_&&(a="b");var b=this.gameInfo_.black&&this.gameInfo_.black.id==this.myUid_||this.gameInfo_.red&&this.gameInfo_.red.id==this.myUid_;this.board_.setState(a,!this.gameInProgress()||!b,this.parseMoves(this.gameInfo_.moves));this.updateStatus();this.refreshMoveHistoryControls();this.createInviteAILink(b&&(!this.gameInfo_.black||!this.gameInfo_.red))};
Game.prototype.initApplication=function(){var a=document.createElement("span");a.id="gameId";a.appendChild(document.createTextNode(this.currentGameId_));var a="Game "+a.outerHTML,b=new NavBarOptions(this.myUid_,this.myName_);b.titleElementHTML=a;b.menuInviteAI=!0;b.menuFork=!0;initializeNavBar(b);this.redWatch_=new Stopwatch("redStopwatch");this.blackWatch_=new Stopwatch("blackStopwatch");window.setInterval(function(){this.redWatch_.tick();this.blackWatch_.tick()}.bind(this),6E4/this.redWatch_.frequency());
this.board_=new Board(this.onPlayerMove.bind(this));this.refreshGame();window.setInterval(function(){this.requestGameInfo(this.currentGameId_)}.bind(this),1E3)};document.onreadystatechange=function(){"interactive"==document.readyState&&new Game(currentGameId,myUid,myName,gameInfo)};
