var PIECE_NONE=0,PIECE_K=1,PIECE_A=2,PIECE_E=3,PIECE_H=4,PIECE_R=5,PIECE_C=6,PIECE_P=7,PIECE_BK=1,PIECE_BA=2,PIECE_BE=3,PIECE_BH=4,PIECE_BR=5,PIECE_BC=6,PIECE_BP=7,PIECE_RK=9,PIECE_RA=10,PIECE_RE=11,PIECE_RH=12,PIECE_RR=13,PIECE_RC=14,PIECE_RP=15;function isRedPiece(u){return 8<=u}function Move(u,n,d,y,v,p){this.i1=u;this.j1=n;this.i2=d;this.j2=y;this.piece=v||PIECE_NONE;this.capture=p||PIECE_NONE}
function Chess(){function u(){return 0==A.length%2}function n(b){return 8<=b?b-8:b}function d(){t=[];A=[];for(var b=0;10>b;++b)for(t.push([]),j=0;9>j;++j)t[b].push(0);b="rheakaehr 9 1c5c1 p1p1p1p1p 9 9 P1P1P1P1P 1C5C1 9 RHEAKAEHR".split(" ");if(10!=b.length)throw"Malformed fen string: rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";for(i=0;10>i;++i){var c=0;for(k=0;k<b[i].length;++k){if(9<=c)throw"Malformed fen string at row "+i+": rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";
var h=b[i][k];if("0"<=h&&"9">=h)c+=parseInt(b[i][k],10);else{var h=t[i],a=c,w=b[i][k],e=w==w.toLowerCase(),w=w.toLowerCase(),m=0;"k"==w?m=1:"a"==w?m=2:"e"==w?m=3:"h"==w?m=4:"r"==w?m=5:"c"==w?m=6:"p"==w&&(m=7);e||(m+=8);h[a]=m;++c}}}}function y(b,c,h,m){A.push(new Move(b,c,h,m,t[b][c],t[h][m]));t[h][m]=t[b][c];t[b][c]=0;return A[A.length-1]}function v(){var b=A.pop();t[b.i1][b.j1]=t[b.i2][b.j2];t[b.i2][b.j2]=b.capture}function p(b,c){return 0<=b&&10>b&&0<=c&&9>c}function l(b,c){return 3<=c&&5>=c&&
(0<=b&&2>=b||7<=b&&9>=b)}function a(b,c){var h=[];for(r=0;4>r;++r)l(b+m[r],c+e[r])&&h.push(new Move(b,c,b+m[r],c+e[r]));for(delta=-1;1>=delta;delta+=2)for(ii=b+delta;0<=ii&&10>ii&&(n(t[ii][c])==PIECE_K&&h.push(new Move(b,c,ii,c)),0==t[ii][c]);ii+=delta);return h}function x(b,c){var h=[];for(r=0;4>r;++r)l(b+f[r],c+D[r])&&h.push(new Move(b,c,b+f[r],c+D[r]));return h}function F(b,c){var h=[];for(r=0;4>r;++r)p(b+2*f[r],c+2*D[r])&&0==t[b+f[r]][c+D[r]]&&4<b+f[r]&&h.push(new Move(b,c,b+2*f[r],c+2*D[r]));
return h}function B(b,c){var h=[];for(r=0;4>r;++r)!p(b+2*f[r],c+2*D[r])||0!=t[b+f[r]][c+D[r]]||4<b+f[r]||h.push(new Move(b,c,b+2*f[r],c+2*D[r]));return h}function q(b,c){var h=[];[[1,2,0,1],[1,-2,0,-1],[-1,2,0,1],[-1,-2,0,-1],[2,1,1,0],[2,-1,1,0],[-2,1,-1,0],[-2,-1,-1,0]].forEach(function(m){p(b+m[0],c+m[1])&&0==t[b+m[2]][c+m[3]]&&h.push(new Move(b,c,b+m[0],c+m[1]))});return h}function g(b,c){var h=[];for(r=0;4>r;++r){var a,w;a=b+m[r];for(w=c+e[r];p(a,w)&&(h.push(new Move(b,c,a,w)),0==t[a][w]);a+=
m[r],w+=e[r]);}return h}function z(b,c){var h=[];for(r=0;4>r;++r){var a,w,f=!1;a=b+m[r];for(w=c+e[r];p(a,w);a+=m[r],w+=e[r])if(!f&&0==t[a][w])h.push(new Move(b,c,a,w));else if(!f&&0!=t[a][w])f=!0;else if(f&&0!=t[a][w]){h.push(new Move(b,c,a,w));break}}return h}function H(b,c){var h=[];4<b?h.push(new Move(b,c,b-1,c)):(p(b-1,c)&&h.push(new Move(b,c,b-1,c)),p(b,c-1)&&h.push(new Move(b,c,b,c-1)),p(b,c+1)&&h.push(new Move(b,c,b,c+1)));return h}function C(b,c){var h=[];4<b?(p(b+1,c)&&h.push(new Move(b,
c,b+1,c)),p(b,c-1)&&h.push(new Move(b,c,b,c-1)),p(b,c+1)&&h.push(new Move(b,c,b,c+1))):h.push(new Move(b,c,b+1,c));return h}function G(b,c,h){var m=n(t[b][c]),e=isRedPiece(t[b][c]),f=[];1==m?f=a(b,c):2==m?f=x(b,c):3==m?f=e?F(b,c):B(b,c):4==m?f=q(b,c):5==m?f=g(b,c):6==m?f=z(b,c):7==m&&(f=e?H(b,c):C(b,c));f.forEach(function(c){0!=t[c.i2][c.j2]&&isRedPiece(t[c.i2][c.j2])==e||h.push(c)})}function E(b){var c=[];for(i=0;10>i;++i)for(j=0;9>j;++j)0!=t[i][j]&&isRedPiece(t[i][j])==b&&G(i,j,c);return c}this.reset=
d;this.setMoves=function(b){var c=A;d();for(var h=!0,m=0,a=0;a<b.length;++a)y(b[a][0],b[a][1],b[a][2],b[a][3]),h&&c.length>a&&c[a].i1==b[a][0]&&c[a].j1==b[a][1]&&c[a].i2==b[a][2]&&c[a].j2==b[a][3]?++m:h=!1;return m};this.move=y;this.checkMove=function(b,c,h,a){var m=u();if(!E(m).find(function(m,e,f){return m.i1==b&&m.j1==c&&m.i2==h&&m.j2==a}))return!1;if(t[h][a]==(m?PIECE_BK:PIECE_RK))return!0;var e=!1;y(b,c,h,a);E(!m).find(function(c,b,h){return t[c.i2][c.j2]==(m?PIECE_RK:PIECE_BK)})&&(e=!0);v();
return!e};this.moveHistory=function(){for(var b=[],c=0;c<A.length;++c)b.push(A[c]);return b};this.pieceAt=function(b,c){return t[b][c]};this.isRedNext=u;this.numMoves=function(){return A.length};var t=[],A=[];d();var m=[0,1,0,-1],e=[1,0,-1,0],f=[1,1,-1,-1],D=[1,-1,-1,1]};function removeAllChildren(u){for(u=document.getElementById(u);u.lastChild;)u.removeChild(u.lastChild)}
function BoardUI(u){function n(){return document.getElementById("board")}function d(a,e){A&&(e=8-e);return E/2+e*E}function y(a,e){A&&(a=9-a);return 5>e?E/2+a*E:E/2+a*E+t}function v(a,e,f,g,b,c){var h=document.createElementNS(C,"line");h.setAttribute("x1",a);h.setAttribute("y1",e);h.setAttribute("x2",f);h.setAttribute("y2",g);h.setAttribute("class",b);c&&(h.id=c);return h}function p(a,e,f,g,b){var c=d(a,e);a=y(a,e);e=document.createElementNS(C,"circle");e.setAttribute("cx",c);e.setAttribute("cy",
a);e.setAttribute("r",f);e.setAttribute("class",g);b&&(e.id=b);return e}function l(a,e){return"abcdefghi"[e]+(9-a).toString()}function a(a,e,f,g,b){b&&B(e,f);var c=void 0;b&&(c="piece-outer-"+l(e,f));var c=p(e,f,23,"piece-outer",c),h=void 0;b&&(h="piece-inner-"+l(e,f));var h=p(e,f,20,"piece-inner",h),z=G[g],w=void 0;b&&(w="piece-text-"+l(e,f));b=w;w=d(e,f);e=y(e,f);f=document.createElementNS(C,"text");f.style.fontFamily="Roboto,monospace";f.style.fontSize="24px";f.setAttribute("text-anchor","middle");
f.setAttribute("alignment-baseline","central");f.setAttribute("dominant-baseline","middle");f.setAttribute("x",w);f.setAttribute("y",e);f.appendChild(document.createTextNode(z));f.setAttribute("class","piece-text");f.userSelect="none";b&&(f.id=b);isRedPiece(g)?(c.setAttribute("stroke","red"),h.style.stroke="red",f.style.fill="red"):(c.style.stroke="black",h.style.stroke="black",f.style.fill="black");c.style.strokeWidth=2;h.style.strokeWidth=2;c.style.fill="white";h.style.fillOpacity=0;a.appendChild(c);
a.appendChild(h);a.appendChild(f)}function x(a,e){return function(){u(a,e)}}function F(a,e){var f=p(a,e,23,"piece-cover","piece-cover-"+l(a,e));f.style.strokeWidth=0;f.style.fillOpacity=0;f.userSelect="none";f.onmousedown=x(a,e);f.touchend=f.onmousedown;q(f)}function B(a,e){var f="piece-cover-"+l(a,e);null!=document.getElementById(f)&&g(f)}function q(a){n().appendChild(a)}function g(a){n().removeChild(document.getElementById(a))}function z(a,e,f,g){var b;b=d(a,e);a=y(a,e);e=d(f,g);f=y(f,g);b=v(b,
a,e,f,"grid",void 0);b.style.strokeWidth=1;b.style.stroke="gray";q(b)}function H(a){A=a;removeAllChildren("board");for(i=0;9>i;++i)z(0,i,4,i),0!=i&&8!=i||z(4,i,5,i),z(5,i,9,i);for(i=0;10>i;++i)z(i,0,i,8);z(0,3,2,5);z(0,5,2,3);z(7,3,9,5);z(9,3,7,5);for(i=0;10>i;++i)for(j=0;9>j;++j)F(i,j)}this.reset=H;this.drawPieceWithCover=function(m,e,f){a(n(),m,e,f,!0);F(m,e)};this.erasePiece=function(a,e){B(a,e);g("piece-text-"+l(a,e));g("piece-inner-"+l(a,e));g("piece-outer-"+l(a,e));F(a,e)};this.drawColorIndicator=
function(g,e){var f=1;e&&(f+=8);a(g,0,0,f,!1)};this.highlightSquare=function(a,e){var f=d(a,e),g=y(a,e),b=E/6;for(a=-1;1>=a;a+=2){var c=v(f-23,g+23*a,f-23+b,g+23*a,"highlighter",void 0);c.style.strokeWidth=2;c.style.stroke="blue";q(c);c=v(f+23-b,g+23*a,f+23,g+23*a,"highlighter",void 0);c.style.strokeWidth=2;c.style.stroke="blue";q(c)}for(a=-1;1>=a;a+=2)c=v(f+23*a,g-23,f+23*a,g-23+b,"highlighter",void 0),c.style.strokeWidth=2,c.style.stroke="blue",q(c),c=v(f+23*a,g+23-b,f+23*a,g+23,"highlighter",void 0),
c.style.strokeWidth=2,c.style.stroke="blue",q(c)};this.eraseHighlights=function(){for(var a=n().getElementsByClassName("highlighter");0<a.length;)n().removeChild(a[0])};var C="http://www.w3.org/2000/svg",G=" \u5c07 \u58eb \u8c61 \u99ac \u8eca \u7832 \u5352  \u5e25 \u4ed5 \u76f8 \u508c \u4fe5 \u70ae \u5175".split(" "),E=50,t=0,A=!1;H(!1)};function Board(u){function n(){for(var g=0;10>g;++g)for(var d=0;9>d;++d)l.pieceAt(g,d)!=PIECE_NONE&&a.drawPieceWithCover(g,d,l.pieceAt(g,d));q=l.numMoves()}function d(a){a=Math.max(0,a);a=Math.min(l.numMoves(),a);if(a!=q){var d=l.moveHistory();if(a>q)for(var x=q;x<a;++x)v(d[x]);else for(x=q-1;x>=a;--x)0<x?p(d[x],d[x-1]):p(d[x],null);q=a}}function y(a){return a==PIECE_NONE?!1:"r"==x?isRedPiece(a):"b"==x?!isRedPiece(a):!1}function v(g){a.erasePiece(g.i1,g.j1);g.capture&&a.erasePiece(g.i2,g.j2);a.drawPieceWithCover(g.i2,
g.j2,g.piece);a.eraseHighlights();a.highlightSquare(g.i1,g.j1);a.highlightSquare(g.i2,g.j2);B=null}function p(g,d){a.drawPieceWithCover(g.i1,g.j1,g.piece);a.erasePiece(g.i2,g.j2);g.capture&&a.drawPieceWithCover(g.i2,g.j2,g.capture);a.eraseHighlights();d&&(a.highlightSquare(d.i1,d.j1),a.highlightSquare(d.i2,d.j2));B=null}this.setState=function(g,z,v){g!=x&&(x=g,a.reset("b"==g),l.reset(),n(),B=null);F=z;g=l.moveHistory();v=l.setMoves(v);z=q;q==g.length&&(z=l.numMoves());for(z=Math.min(z,l.numMoves());q>
v;--q){var u=q-1;0<u?p(g[u],g[u-1]):p(g[u],null)}d(z)};this.showMove=d;this.isRedNext=function(){return l.isRedNext()};this.numMoves=function(){return l.numMoves()};this.numMovesShown=function(){return q};var l=new Chess,a=new BoardUI(function(g,d){if(!F){var n=l.isRedNext();if(("r"==x&&n||"b"==x&&!n)&&q==l.numMoves())if(B)if(l.checkMove(B[0],B[1],g,d)){var n=B[0],p=B[1];v(l.move(n,p,g,d));++q;u(n,p,g,d)}else y(l.pieceAt(g,d))&&(a.eraseHighlights(),B=[g,d],a.highlightSquare(g,d));else y(l.pieceAt(g,
d))&&(a.eraseHighlights(),B=[g,d],a.highlightSquare(g,d))}}),x="r",F=!0,B=null,q=0;a.drawColorIndicator(document.getElementById("redIndicator"),!0);a.drawColorIndicator(document.getElementById("blackIndicator"),!1);n()};function Stopwatch(u){function n(){return document.getElementById(u)}function d(){if(p){var a=document.getElementById(u+"Hand"),d=.8*v,n=l/y*2*Math.PI;a.setAttribute("x2",d*Math.sin(n));a.setAttribute("y2",-d*Math.cos(n));++l;l%=y}}this.start=function(){p||(p=!0,l=0,d(),n().style.visibility="visible")};this.stop=function(){p=!1;n().style.visibility="hidden"};this.tick=d;this.frequency=function(){return y};var y=60,v=20,p=!1,l=0;(function(){var a=document.createElementNS("http://www.w3.org/2000/svg",
"circle");a.setAttribute("cx",0);a.setAttribute("cy",0);a.setAttribute("r",v);a.style.stroke="black";a.style.strokeWidth=2;a.style.fillOpacity=0;n().appendChild(a);a=document.createElementNS("http://www.w3.org/2000/svg","line");a.setAttribute("x1",0);a.setAttribute("y1",-v);a.setAttribute("x2",0);a.setAttribute("y2",-v-6);a.style.strokeWidth=4;a.style.stroke="black";n().appendChild(a);a=document.createElementNS("http://www.w3.org/2000/svg","rect");a.setAttribute("x",-3);a.setAttribute("y",-v-6-4);
a.setAttribute("width",6);a.setAttribute("height",4);a.style.strokeWidth=.5;a.style.stroke="black";a.style.fillOpacity=0;n().appendChild(a);a=document.createElementNS("http://www.w3.org/2000/svg","circle");a.setAttribute("cx",0);a.setAttribute("cy",-v-6-2);a.setAttribute("r",6);a.style.stroke="black";a.style.strokeWidth=1;a.style.fillOpacity=0;n().appendChild(a);for(a=-3;3>=a;a+=1){var d=document.createElementNS("http://www.w3.org/2000/svg","line");d.setAttribute("x1",a);d.setAttribute("y1",-v-6-
4);d.setAttribute("x2",a);d.setAttribute("y2",-v-6);d.style.strokeWidth=.2;d.style.stroke="black";n().appendChild(d)}for(a=0;12>a;++a){var d=document.createElementNS("http://www.w3.org/2000/svg","line"),l=a/12*2*Math.PI,p=v,q=.7*v;d.setAttribute("x1",p*Math.sin(l));d.setAttribute("y1",-p*Math.cos(l));d.setAttribute("x2",q*Math.sin(l));d.setAttribute("y2",-q*Math.cos(l));d.style.strokeWidth=1;d.style.stroke="black";n().appendChild(d)}for(a=0;60>a;++a)d=document.createElementNS("http://www.w3.org/2000/svg",
"line"),l=a/60*2*Math.PI,p=v,q=.85*v,d.setAttribute("x1",p*Math.sin(l)),d.setAttribute("y1",-p*Math.cos(l)),d.setAttribute("x2",q*Math.sin(l)),d.setAttribute("y2",-q*Math.cos(l)),d.style.strokeWidth=.5,d.style.stroke="black",n().appendChild(d);a=document.createElementNS("http://www.w3.org/2000/svg","line");a.id=u+"Hand";a.setAttribute("x1",0);a.setAttribute("y1",0);a.setAttribute("x2",0);a.setAttribute("y2",.8*-v);a.style.strokeWidth=1.5;a.style.stroke="black";n().appendChild(a);n().style.visibility=
"hidden"})()};String.prototype.endsWith||(String.prototype.endsWith=function(u,n){var d=this.toString();if(void 0===n||n>d.length)n=d.length;n-=u.length;d=d.indexOf(u,n);return-1!==d&&d===n});
function Game(u,n,d){function y(a,h,d,e,g,m,n){var l=new XMLHttpRequest;l.onreadystatechange=function(){if(4==l.readyState){var a=b.indexOf(d);if(-1!=a){b.splice(a,1);for(var c=f+1;c<=D;++c)if(a=b.indexOf(c),-1==a)f=c;else break;requestResolved=!0}else requestResolved=!1;200<=l.status&&299>=l.status?requestResolved||D==d?m(l.responseText):console.log("Dropped response from an old request."):n&&n(l.responseText)}};l.open(a,h,!0);e&&l.setRequestHeader("Content-type",e);g?l.send(g):l.send()}function v(a,
h,d,e){++D;b.push(D);y("POST",a,D,"application/x-www-form-urlencoded; charset=UTF-8",h,d,e)}function p(a){if("fail"==a)alert("Operation failed");else try{var b=JSON.parse(a);b.gameinfo&&("success"!==b.status&&console.log("last update failed"),b=b.gameinfo);d=b;E()}catch(e){console.log("Unrecognized server response: "+a)}}function l(a){a=a.split("/");for(var b=[],d=1;d<a.length;++d){var e=a[d];if("R"==e||"B"==e)break;b.push([parseInt(e[0],10),parseInt(e[1],10),parseInt(e[2],10),parseInt(e[3],10)])}return b}
function a(a,b,e,f){var g=d;a=[a,b,e,f];g.moves+="/"+(""+a[0]+a[1]+a[2]+a[3]);H();v("/gameinfo","uid="+n+"&sid="+F("sid")+"&gid="+u+"&moves="+d.moves,p,x);G()}function x(a){console.log("Retrieve game info failed")}function F(a){a+="=";for(var b=document.cookie.split(";"),d=0;d<b.length;++d){for(var e=b[d];" "==e.charAt(0);)e=e.substring(1);if(0==e.indexOf(a))return e.substring(a.length,e.length)}return""}function B(a){var b=document.getElementById(a+"-player"),d=document.getElementById(a+"-sit-link");
b.removeChild(d);b.appendChild(document.createTextNode("sitting down..."));v("/gameinfo","uid="+n+"&sid="+F("sid")+"&gid="+u+"&sit="+a,p,x)}function q(a,b,d,e,f){var g=document.createElement("a");g.id=a;b&&(g.className=b);g.href=d;e&&(g.onclick=e);g.appendChild(document.createTextNode(f));return g}function g(a){var b=document.createElement("sup");b.className="hint-you";a?b.appendChild(document.createTextNode(" ")):b.appendChild(document.createTextNode("you"));return b}function z(){removeAllChildren("red-player");
removeAllChildren("black-player");if(void 0!==d.red&&null!==d.red){var a=document.getElementById("red-player"),b=document.createElement("span");b.appendChild(document.createTextNode(d.red.name));a.appendChild(b);a.appendChild(g(d.red.id!=n))}else b=q("red-sit-link","sit-link","#",function(){B("red");return!1},"sit here"),document.getElementById("red-player").appendChild(b);void 0!==d.black&&null!==d.black?(a=document.getElementById("black-player"),b=document.createElement("span"),b.appendChild(document.createTextNode(d.black.name)),
a.appendChild(b),a.appendChild(g(d.black.id!=n))):(b=q("black-sit-link","sit-link","#",function(){B("black");return!1},"sit here"),document.getElementById("black-player").appendChild(b))}function H(){var a=document.getElementById("waitingStatus"),b=document.getElementById("playingStatus"),f=document.getElementById("redWonStatus"),g=document.getElementById("blackWonStatus");a.style.display="none";b.style.display="none";f.style.display="none";g.style.display="none";d.moves.endsWith("R")?f.style.display=
"inline-block":d.moves.endsWith("B")?g.style.display="inline-block":d.red&&d.black?(b.style.display="inline-block",e.isRedNext()?(A.start(),m.stop()):(m.start(),A.stop())):a.style.display="inline-block"}function C(a,b){var d=document.createElement("td");d.appendChild(b);a.appendChild(d)}function G(){removeAllChildren("move-history");var a=document.getElementById("move-history"),b=document.createElement("table");b.id="moveHistoryControls";var d=document.createElement("tr");b.appendChild(d);0<e.numMovesShown()?
(C(d,q("move-history-first",void 0,"#",function(){e.showMove(0);G();return!1},"first")),C(d,q("move-history-prev",void 0,"#",function(){e.showMove(e.numMovesShown()-1);G();return!1},"prev"))):(C(d,document.createTextNode("first")),C(d,document.createTextNode("prev")));C(d,document.createTextNode(""+e.numMovesShown()+" / "+e.numMoves()));e.numMovesShown()<e.numMoves()?(C(d,q("move-history-next",void 0,"#",function(){e.showMove(e.numMovesShown()+1);G();return!1},"next")),C(d,q("move-history-last",void 0,
"#",function(){e.showMove(e.numMoves());G();return!1},"last"))):(C(d,document.createTextNode("next")),C(d,document.createTextNode("last")));a.appendChild(b);b=document.createElement("div");b.id="moveHistoryFork";b.appendChild(q("move-history-fork-link",void 0,"/fork/"+u+"/"+e.numMovesShown().toString(),void 0,"fork"));b.appendChild(document.createTextNode(" current position"));a.appendChild(b)}function E(){z();var a="r";d.black&&d.black.id==n&&(a="b");var b=d.black&&d.black.id==n||d.red&&d.red.id==
n;e.setState(a,!(d.red&&d.black&&!d.moves.endsWith("R")&&!d.moves.endsWith("B"))||!b,l(d.moves));H();G()}function t(){var a=document.getElementById("board");.81*window.innerHeight<=window.innerWidth?(a.style.removeProperty("width"),a.style.height="90vh"):(a.style.width="100vw",a.style.removeProperty("height"))}var A,m,e,f=0,D=0,b=[];(function(){A=new Stopwatch("redStopwatch");m=new Stopwatch("blackStopwatch");window.setInterval(function(){A.tick();m.tick()},6E4/A.frequency());window.onload=t;window.onresize=
t;e=new Board(a);E();window.setInterval(function(){y("GET","/gameinfo?gid="+u,f,void 0,void 0,p,x)},1E3)})()}document.onreadystatechange=function(){"interactive"==document.readyState&&new Game(currentGameId,myUid,gameInfo)};
