var PIECE_NONE=0,PIECE_K=1,PIECE_A=2,PIECE_E=3,PIECE_H=4,PIECE_R=5,PIECE_C=6,PIECE_P=7,PIECE_BK=1,PIECE_BA=2,PIECE_BE=3,PIECE_BH=4,PIECE_BR=5,PIECE_BC=6,PIECE_BP=7,PIECE_RK=9,PIECE_RA=10,PIECE_RE=11,PIECE_RH=12,PIECE_RR=13,PIECE_RC=14,PIECE_RP=15;function isRedPiece(t){return 8<=t}function Move(t,l,f,x,u,q){this.i1=t;this.j1=l;this.i2=f;this.j2=x;this.piece=u||PIECE_NONE;this.capture=q||PIECE_NONE}
function Chess(){function t(){return 0==A.length%2}function l(b){return 8<=b?b-8:b}function f(){p=[];A=[];for(var b=0;10>b;++b)for(p.push([]),j=0;9>j;++j)p[b].push(0);b="rheakaehr 9 1c5c1 p1p1p1p1p 9 9 P1P1P1P1P 1C5C1 9 RHEAKAEHR".split(" ");if(10!=b.length)throw"Malformed fen string: rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";for(i=0;10>i;++i){var c=0;for(k=0;k<b[i].length;++k){if(9<=c)throw"Malformed fen string at row "+i+": rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";
var a=b[i][k];if("0"<=a&&"9">=a)c+=parseInt(b[i][k],10);else{var a=p[i],n=c,h=b[i][k],y=h==h.toLowerCase(),h=h.toLowerCase(),e=0;"k"==h?e=1:"a"==h?e=2:"e"==h?e=3:"h"==h?e=4:"r"==h?e=5:"c"==h?e=6:"p"==h&&(e=7);y||(e+=8);a[n]=e;++c}}}}function x(b,c,a,n){A.push(new Move(b,c,a,n,p[b][c],p[a][n]));p[a][n]=p[b][c];p[b][c]=0;return A[A.length-1]}function u(){var b=A.pop();p[b.i1][b.j1]=p[b.i2][b.j2];p[b.i2][b.j2]=b.capture}function q(b,c){return 0<=b&&10>b&&0<=c&&9>c}function m(b,c){return 3<=c&&5>=c&&
(0<=b&&2>=b||7<=b&&9>=b)}function a(b,c){var a=[];for(r=0;4>r;++r)m(b+y[r],c+D[r])&&a.push(new Move(b,c,b+y[r],c+D[r]));for(delta=-1;1>=delta;delta+=2)for(ii=b+delta;0<=ii&&10>ii&&(l(p[ii][c])==PIECE_K&&a.push(new Move(b,c,ii,c)),0==p[ii][c]);ii+=delta);return a}function C(b,c){var a=[];for(r=0;4>r;++r)m(b+e[r],c+w[r])&&a.push(new Move(b,c,b+e[r],c+w[r]));return a}function E(b,c){var a=[];for(r=0;4>r;++r)q(b+2*e[r],c+2*w[r])&&0==p[b+e[r]][c+w[r]]&&4<b+e[r]&&a.push(new Move(b,c,b+2*e[r],c+2*w[r]));
return a}function B(b,c){var a=[];for(r=0;4>r;++r)!q(b+2*e[r],c+2*w[r])||0!=p[b+e[r]][c+w[r]]||4<b+e[r]||a.push(new Move(b,c,b+2*e[r],c+2*w[r]));return a}function v(b,c){var a=[];[[1,2,0,1],[1,-2,0,-1],[-1,2,0,1],[-1,-2,0,-1],[2,1,1,0],[2,-1,1,0],[-2,1,-1,0],[-2,-1,-1,0]].forEach(function(n){q(b+n[0],c+n[1])&&0==p[b+n[2]][c+n[3]]&&a.push(new Move(b,c,b+n[0],c+n[1]))});return a}function d(b,c){var a=[];for(r=0;4>r;++r){var n,h;n=b+y[r];for(h=c+D[r];q(n,h)&&(a.push(new Move(b,c,n,h)),0==p[n][h]);n+=
y[r],h+=D[r]);}return a}function g(b,c){var a=[];for(r=0;4>r;++r){var n,h,e=!1;n=b+y[r];for(h=c+D[r];q(n,h);n+=y[r],h+=D[r])if(!e&&0==p[n][h])a.push(new Move(b,c,n,h));else if(!e&&0!=p[n][h])e=!0;else if(e&&0!=p[n][h]){a.push(new Move(b,c,n,h));break}}return a}function F(b,c){var a=[];4<b?a.push(new Move(b,c,b-1,c)):(q(b-1,c)&&a.push(new Move(b,c,b-1,c)),q(b,c-1)&&a.push(new Move(b,c,b,c-1)),q(b,c+1)&&a.push(new Move(b,c,b,c+1)));return a}function G(b,c){var a=[];4<b?(q(b+1,c)&&a.push(new Move(b,
c,b+1,c)),q(b,c-1)&&a.push(new Move(b,c,b,c-1)),q(b,c+1)&&a.push(new Move(b,c,b,c+1))):a.push(new Move(b,c,b+1,c));return a}function H(b,c,e){var n=l(p[b][c]),h=isRedPiece(p[b][c]),y=[];1==n?y=a(b,c):2==n?y=C(b,c):3==n?y=h?E(b,c):B(b,c):4==n?y=v(b,c):5==n?y=d(b,c):6==n?y=g(b,c):7==n&&(y=h?F(b,c):G(b,c));y.forEach(function(b){0!=p[b.i2][b.j2]&&isRedPiece(p[b.i2][b.j2])==h||e.push(b)})}function z(b){var c=[];for(i=0;10>i;++i)for(j=0;9>j;++j)0!=p[i][j]&&isRedPiece(p[i][j])==b&&H(i,j,c);return c}this.reset=
f;this.setMoves=function(b){var c=A;f();for(var a=!0,n=0,h=0;h<b.length;++h)x(b[h][0],b[h][1],b[h][2],b[h][3]),a&&c.length>h&&c[h].i1==b[h][0]&&c[h].j1==b[h][1]&&c[h].i2==b[h][2]&&c[h].j2==b[h][3]?++n:a=!1;return n};this.move=x;this.checkMove=function(b,c,a,n){var h=t();if(!z(h).find(function(h,e,y){return h.i1==b&&h.j1==c&&h.i2==a&&h.j2==n}))return!1;if(p[a][n]==(h?PIECE_BK:PIECE_RK))return!0;var e=!1;x(b,c,a,n);z(!h).find(function(b,c,a){return p[b.i2][b.j2]==(h?PIECE_RK:PIECE_BK)})&&(e=!0);u();
return!e};this.moveHistory=function(){for(var b=[],c=0;c<A.length;++c)b.push(A[c]);return b};this.pieceAt=function(b,c){return p[b][c]};this.isRedNext=t;this.numMoves=function(){return A.length};var p=[],A=[];f();var y=[0,1,0,-1],D=[1,0,-1,0],e=[1,1,-1,-1],w=[1,-1,-1,1]};function removeAllChildren(t){for(t=document.getElementById(t);t.lastChild;)t.removeChild(t.lastChild)}
function BoardUI(t){function l(){return document.getElementById("board")}function f(a,d){A&&(d=8-d);return z/2+d*z}function x(a,d){A&&(a=9-a);return 5>d?z/2+a*z:z/2+a*z+p}function u(a,d,e,f,b,c){var g=document.createElementNS(G,"line");g.setAttribute("x1",a);g.setAttribute("y1",d);g.setAttribute("x2",e);g.setAttribute("y2",f);g.setAttribute("class",b);c&&(g.id=c);return g}function q(a,d,e,g,b){var c=f(a,d);a=x(a,d);d=document.createElementNS(G,"circle");d.setAttribute("cx",c);d.setAttribute("cy",
a);d.setAttribute("r",e);d.setAttribute("class",g);b&&(d.id=b);return d}function m(a,d){return"abcdefghi"[d]+(9-a).toString()}function a(a,d,e,g,b){b&&B(d,e);var c=void 0;b&&(c="piece-outer-"+m(d,e));var c=q(d,e,23,"piece-outer",c),l=void 0;b&&(l="piece-inner-"+m(d,e));var l=q(d,e,20,"piece-inner",l),n=H[g],h=void 0;b&&(h="piece-text-"+m(d,e));b=h;h=f(d,e);d=x(d,e);e=document.createElementNS(G,"text");e.style.fontFamily="Roboto,monospace";e.style.fontSize="24px";e.setAttribute("text-anchor","middle");
e.setAttribute("alignment-baseline","central");e.setAttribute("dominant-baseline","middle");e.setAttribute("x",h);e.setAttribute("y",d);e.appendChild(document.createTextNode(n));e.setAttribute("class","piece-text");e.userSelect="none";b&&(e.id=b);isRedPiece(g)?(c.setAttribute("stroke","red"),l.style.stroke="red",e.style.fill="red"):(c.style.stroke="black",l.style.stroke="black",e.style.fill="black");c.style.strokeWidth=2;l.style.strokeWidth=2;c.style.fill="white";l.style.fillOpacity=0;a.appendChild(c);
a.appendChild(l);a.appendChild(e)}function C(a,d){return function(){t(a,d)}}function E(a,d){var e=q(a,d,23,"piece-cover","piece-cover-"+m(a,d));e.style.strokeWidth=0;e.style.fillOpacity=0;e.userSelect="none";e.onmousedown=C(a,d);e.touchend=e.onmousedown;v(e)}function B(a,g){var e="piece-cover-"+m(a,g);null!=document.getElementById(e)&&d(e)}function v(a){l().appendChild(a)}function d(a){l().removeChild(document.getElementById(a))}function g(a,d,e,g){var b;b=f(a,d);a=x(a,d);d=f(e,g);e=x(e,g);b=u(b,
a,d,e,"grid",void 0);b.style.strokeWidth=1;b.style.stroke="gray";v(b)}function F(a){A=a;removeAllChildren("board");for(i=0;9>i;++i)g(0,i,4,i),0!=i&&8!=i||g(4,i,5,i),g(5,i,9,i);for(i=0;10>i;++i)g(i,0,i,8);g(0,3,2,5);g(0,5,2,3);g(7,3,9,5);g(9,3,7,5);for(i=0;10>i;++i)for(j=0;9>j;++j)E(i,j)}this.reset=F;this.drawPieceWithCover=function(d,g,e){a(l(),d,g,e,!0);E(d,g)};this.erasePiece=function(a,g){B(a,g);d("piece-text-"+m(a,g));d("piece-inner-"+m(a,g));d("piece-outer-"+m(a,g));E(a,g)};this.drawColorIndicator=
function(d,g){var e=1;g&&(e+=8);a(d,0,0,e,!1)};this.highlightSquare=function(a,d){var e=f(a,d),g=x(a,d),b=z/6;for(a=-1;1>=a;a+=2){var c=u(e-23,g+23*a,e-23+b,g+23*a,"highlighter",void 0);c.style.strokeWidth=2;c.style.stroke="blue";v(c);c=u(e+23-b,g+23*a,e+23,g+23*a,"highlighter",void 0);c.style.strokeWidth=2;c.style.stroke="blue";v(c)}for(a=-1;1>=a;a+=2)c=u(e+23*a,g-23,e+23*a,g-23+b,"highlighter",void 0),c.style.strokeWidth=2,c.style.stroke="blue",v(c),c=u(e+23*a,g+23-b,e+23*a,g+23,"highlighter",void 0),
c.style.strokeWidth=2,c.style.stroke="blue",v(c)};this.eraseHighlights=function(){for(var a=l().getElementsByClassName("highlighter");0<a.length;)l().removeChild(a[0])};var G="http://www.w3.org/2000/svg",H=" \u5c07 \u58eb \u8c61 \u99ac \u8eca \u7832 \u5352  \u5e25 \u4ed5 \u76f8 \u508c \u4fe5 \u70ae \u5175".split(" "),z=50,p=0,A=!1;F(!1)};function Board(t){function l(){for(var d=0;10>d;++d)for(var g=0;9>g;++g)m.pieceAt(d,g)!=PIECE_NONE&&a.drawPieceWithCover(d,g,m.pieceAt(d,g));v=m.numMoves()}function f(a){a=Math.max(0,a);a=Math.min(m.numMoves(),a);if(a!=v){var g=m.moveHistory();if(a>v)for(var f=v;f<a;++f)u(g[f]);else for(f=v-1;f>=a;--f)0<f?q(g[f],g[f-1]):q(g[f],null);v=a}}function x(a){return a==PIECE_NONE?!1:"r"==C?isRedPiece(a):"b"==C?!isRedPiece(a):!1}function u(d){a.erasePiece(d.i1,d.j1);d.capture&&a.erasePiece(d.i2,d.j2);a.drawPieceWithCover(d.i2,
d.j2,d.piece);a.eraseHighlights();a.highlightSquare(d.i1,d.j1);a.highlightSquare(d.i2,d.j2);B=null}function q(d,g){a.drawPieceWithCover(d.i1,d.j1,d.piece);a.erasePiece(d.i2,d.j2);d.capture&&a.drawPieceWithCover(d.i2,d.j2,d.capture);a.eraseHighlights();g&&(a.highlightSquare(g.i1,g.j1),a.highlightSquare(g.i2,g.j2));B=null}this.setState=function(d,g,t){d!=C&&(C=d,a.reset("b"==d),m.reset(),l(),B=null);E=g;d=m.moveHistory();t=m.setMoves(t);g=v;v==d.length&&(g=m.numMoves());for(g=Math.min(g,m.numMoves());v>
t;--v){var u=v-1;0<u?q(d[u],d[u-1]):q(d[u],null)}f(g)};this.showMove=f;this.isRedNext=function(){return m.isRedNext()};this.numMoves=function(){return m.numMoves()};this.numMovesShown=function(){return v};var m=new Chess,a=new BoardUI(function(d,g){if(!E){var f=m.isRedNext();if(("r"==C&&f||"b"==C&&!f)&&v==m.numMoves())if(B)if(m.checkMove(B[0],B[1],d,g)){var f=B[0],l=B[1];u(m.move(f,l,d,g));++v;t(f,l,d,g)}else x(m.pieceAt(d,g))&&(a.eraseHighlights(),B=[d,g],a.highlightSquare(d,g));else x(m.pieceAt(d,
g))&&(a.eraseHighlights(),B=[d,g],a.highlightSquare(d,g))}}),C="r",E=!0,B=null,v=0;a.drawColorIndicator(document.getElementById("redIndicator"),!0);a.drawColorIndicator(document.getElementById("blackIndicator"),!1);l()};function Stopwatch(t){function l(){return document.getElementById(t)}function f(){if(q){var a=document.getElementById(t+"Hand"),f=.8*u,l=m/x*2*Math.PI;a.setAttribute("x2",f*Math.sin(l));a.setAttribute("y2",-f*Math.cos(l));++m;m%=x}}this.start=function(){q||(q=!0,m=0,f(),l().style.visibility="visible")};this.stop=function(){q=!1;l().style.visibility="hidden"};this.tick=f;this.frequency=function(){return x};var x=60,u=20,q=!1,m=0;(function(){var a=document.createElementNS("http://www.w3.org/2000/svg",
"circle");a.setAttribute("cx",0);a.setAttribute("cy",0);a.setAttribute("r",u);a.style.stroke="black";a.style.strokeWidth=2;a.style.fillOpacity=0;l().appendChild(a);a=document.createElementNS("http://www.w3.org/2000/svg","line");a.setAttribute("x1",0);a.setAttribute("y1",-u);a.setAttribute("x2",0);a.setAttribute("y2",-u-6);a.style.strokeWidth=4;a.style.stroke="black";l().appendChild(a);a=document.createElementNS("http://www.w3.org/2000/svg","rect");a.setAttribute("x",-3);a.setAttribute("y",-u-6-4);
a.setAttribute("width",6);a.setAttribute("height",4);a.style.strokeWidth=.5;a.style.stroke="black";a.style.fillOpacity=0;l().appendChild(a);a=document.createElementNS("http://www.w3.org/2000/svg","circle");a.setAttribute("cx",0);a.setAttribute("cy",-u-6-2);a.setAttribute("r",6);a.style.stroke="black";a.style.strokeWidth=1;a.style.fillOpacity=0;l().appendChild(a);for(a=-3;3>=a;a+=1){var f=document.createElementNS("http://www.w3.org/2000/svg","line");f.setAttribute("x1",a);f.setAttribute("y1",-u-6-
4);f.setAttribute("x2",a);f.setAttribute("y2",-u-6);f.style.strokeWidth=.2;f.style.stroke="black";l().appendChild(f)}for(a=0;12>a;++a){var f=document.createElementNS("http://www.w3.org/2000/svg","line"),m=a/12*2*Math.PI,q=u,v=.7*u;f.setAttribute("x1",q*Math.sin(m));f.setAttribute("y1",-q*Math.cos(m));f.setAttribute("x2",v*Math.sin(m));f.setAttribute("y2",-v*Math.cos(m));f.style.strokeWidth=1;f.style.stroke="black";l().appendChild(f)}for(a=0;60>a;++a)f=document.createElementNS("http://www.w3.org/2000/svg",
"line"),m=a/60*2*Math.PI,q=u,v=.85*u,f.setAttribute("x1",q*Math.sin(m)),f.setAttribute("y1",-q*Math.cos(m)),f.setAttribute("x2",v*Math.sin(m)),f.setAttribute("y2",-v*Math.cos(m)),f.style.strokeWidth=.5,f.style.stroke="black",l().appendChild(f);a=document.createElementNS("http://www.w3.org/2000/svg","line");a.id=t+"Hand";a.setAttribute("x1",0);a.setAttribute("y1",0);a.setAttribute("x2",0);a.setAttribute("y2",.8*-u);a.style.strokeWidth=1.5;a.style.stroke="black";l().appendChild(a);l().style.visibility=
"hidden"})()};String.prototype.endsWith||(String.prototype.endsWith=function(t,l){var f=this.toString();if(void 0===l||l>f.length)l=f.length;l-=t.length;f=f.indexOf(t,l);return-1!==f&&f===l});
function Game(t,l,f){function x(a,h,d,f,e,g,l){var m=new XMLHttpRequest;m.onreadystatechange=function(){if(4==m.readyState){var a=I.indexOf(d);if(-1!=a){I.splice(a,1);for(var h=b+1;h<=c;++h)if(a=I.indexOf(h),-1==a)b=h;else break;requestResolved=!0}else requestResolved=!1;200<=m.status&&299>=m.status?requestResolved||c==d?g(m.responseText):console.log("Dropped response from an old request."):l&&l(m.responseText)}};m.open(a,h,!0);f&&m.setRequestHeader("Content-type",f);e?m.send(e):m.send()}function u(a,
b,d,f){++c;I.push(c);x("POST",a,c,"application/x-www-form-urlencoded; charset=UTF-8",b,d,f)}function q(a){if("fail"==a)alert("Operation failed");else try{var b=JSON.parse(a);b.gameinfo&&("success"!==b.status&&console.log("last update failed"),b=b.gameinfo);f=b;A()}catch(c){console.log("Unrecognized server response: "+a)}}function m(a){a=a.split("/");for(var b=[],c=1;c<a.length;++c){var d=a[c];if("R"==d||"B"==d)break;b.push([parseInt(d[0],10),parseInt(d[1],10),parseInt(d[2],10),parseInt(d[3],10)])}return b}
function a(a,b,c,d){var e=f;a=[a,b,c,d];e.moves+="/"+(""+a[0]+a[1]+a[2]+a[3]);H();u("/gameinfo","uid="+l+"&sid="+E("sid")+"&gid="+t+"&moves="+f.moves,q,C);p()}function C(a){console.log("Retrieve game info failed")}function E(a){a+="=";for(var b=document.cookie.split(";"),c=0;c<b.length;++c){for(var d=b[c];" "==d.charAt(0);)d=d.substring(1);if(0==d.indexOf(a))return d.substring(a.length,d.length)}return""}function B(a){removeAllChildren("invite-ai-container");var b=g("invite-ai-link",null,"#",function(){v("invite-ai-link");
u("/invite_ai","uid="+l+"&sid="+E("sid")+"&gid="+t,q,C);return!1},"invite Blur");document.getElementById("invite-ai-container").appendChild(b);a||v("invite-ai-link")}function v(a){var b=document.getElementById(a);a=b.parentElement;var c=b.innerText,d=b.classList;a.removeChild(b);b=document.createElement("span");b.classList=d;b.classList.add("disabled-link");b.appendChild(document.createTextNode(c));a.appendChild(b)}function d(a){v(a+"-sit-link");u("/gameinfo","uid="+l+"&sid="+E("sid")+"&gid="+t+"&sit="+
a,q,C)}function g(a,b,c,d,f){var e=document.createElement("a");e.id=a;b&&(e.className=b);e.href=c;d&&(e.onclick=d);e.appendChild(document.createTextNode(f));return e}function F(a){var b=document.createElement("sup");b.className="hint-you";a?b.appendChild(document.createTextNode(" ")):b.appendChild(document.createTextNode("you"));return b}function G(){removeAllChildren("red-player");removeAllChildren("black-player");if(void 0!==f.red&&null!==f.red){var a=document.getElementById("red-player"),b=document.createElement("span");
b.appendChild(document.createTextNode(f.red.name));a.appendChild(b);a.appendChild(F(f.red.id!=l))}else b=g("red-sit-link","sit-link","#",function(){d("red");return!1},"sit here"),document.getElementById("red-player").appendChild(b);void 0!==f.black&&null!==f.black?(a=document.getElementById("black-player"),b=document.createElement("span"),b.appendChild(document.createTextNode(f.black.name)),a.appendChild(b),a.appendChild(F(f.black.id!=l))):(b=g("black-sit-link","sit-link","#",function(){d("black");
return!1},"sit here"),document.getElementById("black-player").appendChild(b))}function H(){var a=document.getElementById("waitingStatus"),b=document.getElementById("playingStatus"),c=document.getElementById("redWonStatus"),d=document.getElementById("blackWonStatus");a.style.display="none";b.style.display="none";c.style.display="none";d.style.display="none";f.moves.endsWith("R")?c.style.display="inline-block":f.moves.endsWith("B")?d.style.display="inline-block":f.red&&f.black?(b.style.display="inline-block",
w.isRedNext()?(D.start(),e.stop()):(e.start(),D.stop())):a.style.display="inline-block"}function z(a,b){var c=document.createElement("td");c.appendChild(b);a.appendChild(c)}function p(){removeAllChildren("move-history");var a=document.getElementById("move-history"),b=document.createElement("table");b.id="moveHistoryControls";var c=document.createElement("tr");b.appendChild(c);0<w.numMovesShown()?(z(c,g("move-history-first",void 0,"#",function(){w.showMove(0);p();return!1},"first")),z(c,g("move-history-prev",
void 0,"#",function(){w.showMove(w.numMovesShown()-1);p();return!1},"prev"))):(z(c,document.createTextNode("first")),z(c,document.createTextNode("prev")));z(c,document.createTextNode(""+w.numMovesShown()+" / "+w.numMoves()));w.numMovesShown()<w.numMoves()?(z(c,g("move-history-next",void 0,"#",function(){w.showMove(w.numMovesShown()+1);p();return!1},"next")),z(c,g("move-history-last",void 0,"#",function(){w.showMove(w.numMoves());p();return!1},"last"))):(z(c,document.createTextNode("next")),z(c,document.createTextNode("last")));
a.appendChild(b);document.getElementById("forkGame");removeAllChildren("forkGame");forkGame.appendChild(g("move-history-fork-link",void 0,"/fork/"+t+"/"+w.numMovesShown().toString(),void 0,"fork at move "+w.numMovesShown()))}function A(){G();var a="r";f.black&&f.black.id==l&&(a="b");var b=f.black&&f.black.id==l||f.red&&f.red.id==l;w.setState(a,!(f.red&&f.black&&!f.moves.endsWith("R")&&!f.moves.endsWith("B"))||!b,m(f.moves));H();p();B(b&&(!f.black||!f.red))}function y(){var a=document.getElementById("board");
.81*window.innerHeight<=window.innerWidth?(a.style.removeProperty("width"),a.style.height="90vh"):(a.style.width="100vw",a.style.removeProperty("height"))}var D,e,w,b=0,c=0,I=[];(function(){D=new Stopwatch("redStopwatch");e=new Stopwatch("blackStopwatch");window.setInterval(function(){D.tick();e.tick()},6E4/D.frequency());window.onload=y;window.onresize=y;w=new Board(a);A();window.setInterval(function(){x("GET","/gameinfo?gid="+t,b,void 0,void 0,q,C)},1E3)})()}
function toggleMenu(){var t=document.getElementById("menu-text"),l=document.getElementById("menu-content");"grid"==l.style.display?(l.style.display="none",t.innerHTML='menu <span class="menu-toggle">[+]</span>'):(l.style.display="grid",t.innerHTML='menu <span class="menu-toggle">[-]</span>')}document.onreadystatechange=function(){"interactive"==document.readyState&&new Game(currentGameId,myUid,gameInfo)};
