var PIECE_NONE=0,PIECE_K=1,PIECE_A=2,PIECE_E=3,PIECE_H=4,PIECE_R=5,PIECE_C=6,PIECE_P=7,PIECE_BK=1,PIECE_BA=2,PIECE_BE=3,PIECE_BH=4,PIECE_BR=5,PIECE_BC=6,PIECE_BP=7,PIECE_RK=9,PIECE_RA=10,PIECE_RE=11,PIECE_RH=12,PIECE_RR=13,PIECE_RC=14,PIECE_RP=15;function isRedPiece(q){return 8<=q}function Move(q,l,d,x,v,p){this.i1=q;this.j1=l;this.i2=d;this.j2=x;this.piece=v||PIECE_NONE;this.capture=p||PIECE_NONE}
function Chess(){function q(){return 0==y.length%2}function l(b){return 8<=b?b-8:b}function d(){u=[];y=[];for(var b=0;10>b;++b)for(u.push([]),j=0;9>j;++j)u[b].push(0);b="rheakaehr 9 1c5c1 p1p1p1p1p 9 9 P1P1P1P1P 1C5C1 9 RHEAKAEHR".split(" ");if(10!=b.length)throw"Malformed fen string: rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";for(i=0;10>i;++i){var c=0;for(k=0;k<b[i].length;++k){if(9<=c)throw"Malformed fen string at row "+i+": rheakaehr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RHEAKAEHR";
var h=b[i][k];if("0"<=h&&"9">=h)c+=parseInt(b[i][k],10);else{var h=u[i],a=c,w=b[i][k],e=w==w.toLowerCase(),w=w.toLowerCase(),m=0;"k"==w?m=1:"a"==w?m=2:"e"==w?m=3:"h"==w?m=4:"r"==w?m=5:"c"==w?m=6:"p"==w&&(m=7);e||(m+=8);h[a]=m;++c}}}}function x(b,c,h,m){y.push(new Move(b,c,h,m,u[b][c],u[h][m]));u[h][m]=u[b][c];u[b][c]=0;return y[y.length-1]}function v(){var b=y.pop();u[b.i1][b.j1]=u[b.i2][b.j2];u[b.i2][b.j2]=b.capture}function p(b,c){return 0<=b&&10>b&&0<=c&&9>c}function n(b,c){return 3<=c&&5>=c&&
(0<=b&&2>=b||7<=b&&9>=b)}function a(b,c){var h=[];for(r=0;4>r;++r)n(b+m[r],c+e[r])&&h.push(new Move(b,c,b+m[r],c+e[r]));for(delta=-1;1>=delta;delta+=2)for(ii=b+delta;0<=ii&&10>ii&&(l(u[ii][c])==PIECE_K&&h.push(new Move(b,c,ii,c)),0==u[ii][c]);ii+=delta);return h}function B(b,c){var h=[];for(r=0;4>r;++r)n(b+f[r],c+C[r])&&h.push(new Move(b,c,b+f[r],c+C[r]));return h}function F(b,c){var h=[];for(r=0;4>r;++r)p(b+2*f[r],c+2*C[r])&&0==u[b+f[r]][c+C[r]]&&4<b+f[r]&&h.push(new Move(b,c,b+2*f[r],c+2*C[r]));
return h}function A(b,c){var h=[];for(r=0;4>r;++r)!p(b+2*f[r],c+2*C[r])||0!=u[b+f[r]][c+C[r]]||4<b+f[r]||h.push(new Move(b,c,b+2*f[r],c+2*C[r]));return h}function t(b,c){var h=[];[[1,2,0,1],[1,-2,0,-1],[-1,2,0,1],[-1,-2,0,-1],[2,1,1,0],[2,-1,1,0],[-2,1,-1,0],[-2,-1,-1,0]].forEach(function(m){p(b+m[0],c+m[1])&&0==u[b+m[2]][c+m[3]]&&h.push(new Move(b,c,b+m[0],c+m[1]))});return h}function g(b,c){var h=[];for(r=0;4>r;++r){var a,w;a=b+m[r];for(w=c+e[r];p(a,w)&&(h.push(new Move(b,c,a,w)),0==u[a][w]);a+=
m[r],w+=e[r]);}return h}function D(b,c){var h=[];for(r=0;4>r;++r){var a,w,f=!1;a=b+m[r];for(w=c+e[r];p(a,w);a+=m[r],w+=e[r])if(!f&&0==u[a][w])h.push(new Move(b,c,a,w));else if(!f&&0!=u[a][w])f=!0;else if(f&&0!=u[a][w]){h.push(new Move(b,c,a,w));break}}return h}function H(b,c){var h=[];4<b?h.push(new Move(b,c,b-1,c)):(p(b-1,c)&&h.push(new Move(b,c,b-1,c)),p(b,c-1)&&h.push(new Move(b,c,b,c-1)),p(b,c+1)&&h.push(new Move(b,c,b,c+1)));return h}function z(b,c){var h=[];4<b?(p(b+1,c)&&h.push(new Move(b,
c,b+1,c)),p(b,c-1)&&h.push(new Move(b,c,b,c-1)),p(b,c+1)&&h.push(new Move(b,c,b,c+1))):h.push(new Move(b,c,b+1,c));return h}function G(b,c,h){var m=l(u[b][c]),e=isRedPiece(u[b][c]),f=[];1==m?f=a(b,c):2==m?f=B(b,c):3==m?f=e?F(b,c):A(b,c):4==m?f=t(b,c):5==m?f=g(b,c):6==m?f=D(b,c):7==m&&(f=e?H(b,c):z(b,c));f.forEach(function(c){0!=u[c.i2][c.j2]&&isRedPiece(u[c.i2][c.j2])==e||h.push(c)})}function E(b){var c=[];for(i=0;10>i;++i)for(j=0;9>j;++j)0!=u[i][j]&&isRedPiece(u[i][j])==b&&G(i,j,c);return c}this.reset=
d;this.setMoves=function(b){var c=y;d();for(var h=!0,m=0,a=0;a<b.length;++a)x(b[a][0],b[a][1],b[a][2],b[a][3]),h&&c.length>a&&c[a].i1==b[a][0]&&c[a].j1==b[a][1]&&c[a].i2==b[a][2]&&c[a].j2==b[a][3]?++m:h=!1;return m};this.move=x;this.checkMove=function(b,c,h,a){var m=q();if(!E(m).find(function(m,e,f){return m.i1==b&&m.j1==c&&m.i2==h&&m.j2==a}))return!1;if(u[h][a]==(m?PIECE_BK:PIECE_RK))return!0;var e=!1;x(b,c,h,a);E(!m).find(function(c,b,a){return u[c.i2][c.j2]==(m?PIECE_RK:PIECE_BK)})&&(e=!0);v();
return!e};this.moveHistory=function(){for(var b=[],c=0;c<y.length;++c)b.push(y[c]);return b};this.pieceAt=function(b,c){return u[b][c]};this.isRedNext=q;this.numMoves=function(){return y.length};var u=[],y=[];d();var m=[0,1,0,-1],e=[1,0,-1,0],f=[1,1,-1,-1],C=[1,-1,-1,1]};function removeAllChildren(q){for(q=document.getElementById(q);q.lastChild;)q.removeChild(q.lastChild)}
function BoardUI(q){function l(){return document.getElementById("board")}function d(a,e){y&&(e=8-e);return E/2+e*E}function x(a,e){y&&(a=9-a);return 5>e?E/2+a*E:E/2+a*E+u}function v(a,e,f,g,b,c){var h=document.createElementNS(z,"line");h.setAttribute("x1",a);h.setAttribute("y1",e);h.setAttribute("x2",f);h.setAttribute("y2",g);h.setAttribute("class",b);c&&(h.id=c);return h}function p(a,e,f,g,b){var c=d(a,e);a=x(a,e);e=document.createElementNS(z,"circle");e.setAttribute("cx",c);e.setAttribute("cy",
a);e.setAttribute("r",f);e.setAttribute("class",g);b&&(e.id=b);return e}function n(a,e){return"abcdefghi"[e]+(9-a).toString()}function a(a,e,f,g,b){b&&A(e,f);var c=void 0;b&&(c="piece-outer-"+n(e,f));var c=p(e,f,23,"piece-outer",c),h=void 0;b&&(h="piece-inner-"+n(e,f));var h=p(e,f,20,"piece-inner",h),D=G[g],w=void 0;b&&(w="piece-text-"+n(e,f));b=w;w=d(e,f);e=x(e,f);f=document.createElementNS(z,"text");f.style.fontFamily="Roboto,monospace";f.style.fontSize="24px";f.setAttribute("text-anchor","middle");
f.setAttribute("alignment-baseline","central");f.setAttribute("dominant-baseline","middle");f.setAttribute("x",w);f.setAttribute("y",e);f.appendChild(document.createTextNode(D));f.setAttribute("class","piece-text");f.userSelect="none";b&&(f.id=b);isRedPiece(g)?(c.setAttribute("stroke","red"),h.style.stroke="red",f.style.fill="red"):(c.style.stroke="black",h.style.stroke="black",f.style.fill="black");c.style.strokeWidth=2;h.style.strokeWidth=2;c.style.fill="white";h.style.fillOpacity=0;a.appendChild(c);
a.appendChild(h);a.appendChild(f)}function B(a,e){return function(){q(a,e)}}function F(a,e){var f=p(a,e,23,"piece-cover","piece-cover-"+n(a,e));f.style.strokeWidth=0;f.style.fillOpacity=0;f.userSelect="none";f.onmousedown=B(a,e);f.touchend=f.onmousedown;t(f)}function A(a,e){var f="piece-cover-"+n(a,e);null!=document.getElementById(f)&&g(f)}function t(a){l().appendChild(a)}function g(a){l().removeChild(document.getElementById(a))}function D(a,e,f,g){var b;b=d(a,e);a=x(a,e);e=d(f,g);f=x(f,g);b=v(b,
a,e,f,"grid",void 0);b.style.strokeWidth=1;b.style.stroke="gray";t(b)}function H(a){y=a;removeAllChildren("board");for(i=0;9>i;++i)D(0,i,4,i),0!=i&&8!=i||D(4,i,5,i),D(5,i,9,i);for(i=0;10>i;++i)D(i,0,i,8);D(0,3,2,5);D(0,5,2,3);D(7,3,9,5);D(9,3,7,5);for(i=0;10>i;++i)for(j=0;9>j;++j)F(i,j)}this.reset=H;this.drawPieceWithCover=function(m,e,f){a(l(),m,e,f,!0);F(m,e)};this.erasePiece=function(a,e){A(a,e);g("piece-text-"+n(a,e));g("piece-inner-"+n(a,e));g("piece-outer-"+n(a,e));F(a,e)};this.drawColorIndicator=
function(g,e){var f=1;e&&(f+=8);a(g,0,0,f,!1)};this.highlightSquare=function(a,e){var f=d(a,e),g=x(a,e),b=E/6;for(a=-1;1>=a;a+=2){var c=v(f-23,g+23*a,f-23+b,g+23*a,"highlighter",void 0);c.style.strokeWidth=2;c.style.stroke="blue";t(c);c=v(f+23-b,g+23*a,f+23,g+23*a,"highlighter",void 0);c.style.strokeWidth=2;c.style.stroke="blue";t(c)}for(a=-1;1>=a;a+=2)c=v(f+23*a,g-23,f+23*a,g-23+b,"highlighter",void 0),c.style.strokeWidth=2,c.style.stroke="blue",t(c),c=v(f+23*a,g+23-b,f+23*a,g+23,"highlighter",void 0),
c.style.strokeWidth=2,c.style.stroke="blue",t(c)};this.eraseHighlights=function(){for(var a=l().getElementsByClassName("highlighter");0<a.length;)l().removeChild(a[0])};var z="http://www.w3.org/2000/svg",G=" \u5c07 \u58eb \u8c61 \u99ac \u8eca \u7832 \u5352  \u5e25 \u4ed5 \u76f8 \u508c \u4fe5 \u70ae \u5175".split(" "),E=50,u=0,y=!1;H(!1)};function Board(q){function l(){for(var g=0;10>g;++g)for(var d=0;9>d;++d)n.pieceAt(g,d)!=PIECE_NONE&&a.drawPieceWithCover(g,d,n.pieceAt(g,d));t=n.numMoves()}function d(a){a=Math.max(0,a);a=Math.min(n.numMoves(),a);if(a!=t){var d=n.moveHistory();if(a>t)for(var l=t;l<a;++l)v(d[l]);else for(l=t-1;l>=a;--l)0<l?p(d[l],d[l-1]):p(d[l],null);t=a}}function x(a){return a==PIECE_NONE?!1:"r"==B?isRedPiece(a):"b"==B?!isRedPiece(a):!1}function v(g){a.erasePiece(g.i1,g.j1);g.capture&&a.erasePiece(g.i2,g.j2);a.drawPieceWithCover(g.i2,
g.j2,g.piece);a.eraseHighlights();a.highlightSquare(g.i1,g.j1);a.highlightSquare(g.i2,g.j2);A=null}function p(g,d){a.drawPieceWithCover(g.i1,g.j1,g.piece);a.erasePiece(g.i2,g.j2);g.capture&&a.drawPieceWithCover(g.i2,g.j2,g.capture);a.eraseHighlights();d&&(a.highlightSquare(d.i1,d.j1),a.highlightSquare(d.i2,d.j2));A=null}this.setState=function(g,q,v){g!=B&&(B=g,a.reset("b"==g),n.reset(),l(),A=null);F=q;g=n.moveHistory();v=n.setMoves(v);q=t;t==g.length&&(q=n.numMoves());for(q=Math.min(q,n.numMoves());t>
v;--t){var z=t-1;0<z?p(g[z],g[z-1]):p(g[z],null)}d(q)};this.showMove=d;this.isRedNext=function(){return n.isRedNext()};this.numMoves=function(){return n.numMoves()};this.numMovesShown=function(){return t};var n=new Chess,a=new BoardUI(function(g,d){if(!F){var l=n.isRedNext();if(("r"==B&&l||"b"==B&&!l)&&t==n.numMoves())if(A)if(n.checkMove(A[0],A[1],g,d)){var l=A[0],p=A[1];v(n.move(l,p,g,d));++t;q(l,p,g,d)}else x(n.pieceAt(g,d))&&(a.eraseHighlights(),A=[g,d],a.highlightSquare(g,d));else x(n.pieceAt(g,
d))&&(a.eraseHighlights(),A=[g,d],a.highlightSquare(g,d))}}),B="r",F=!0,A=null,t=0;a.drawColorIndicator(document.getElementById("redIndicator"),!0);a.drawColorIndicator(document.getElementById("blackIndicator"),!1);l()};function Stopwatch(q){function l(){return document.getElementById(q)}function d(){if(p){var a=document.getElementById(q+"Hand"),d=.8*v,l=n/x*2*Math.PI;a.setAttribute("x2",d*Math.sin(l));a.setAttribute("y2",-d*Math.cos(l));++n;n%=x}}this.start=function(){p||(p=!0,n=0,d(),l().style.visibility="visible")};this.stop=function(){p=!1;l().style.visibility="hidden"};this.tick=d;this.frequency=function(){return x};var x=60,v=20,p=!1,n=0;(function(){var a=document.createElementNS("http://www.w3.org/2000/svg",
"circle");a.setAttribute("cx",0);a.setAttribute("cy",0);a.setAttribute("r",v);a.style.stroke="black";a.style.strokeWidth=2;a.style.fillOpacity=0;l().appendChild(a);a=document.createElementNS("http://www.w3.org/2000/svg","line");a.setAttribute("x1",0);a.setAttribute("y1",-v);a.setAttribute("x2",0);a.setAttribute("y2",-v-6);a.style.strokeWidth=4;a.style.stroke="black";l().appendChild(a);a=document.createElementNS("http://www.w3.org/2000/svg","rect");a.setAttribute("x",-3);a.setAttribute("y",-v-6-4);
a.setAttribute("width",6);a.setAttribute("height",4);a.style.strokeWidth=.5;a.style.stroke="black";a.style.fillOpacity=0;l().appendChild(a);a=document.createElementNS("http://www.w3.org/2000/svg","circle");a.setAttribute("cx",0);a.setAttribute("cy",-v-6-2);a.setAttribute("r",6);a.style.stroke="black";a.style.strokeWidth=1;a.style.fillOpacity=0;l().appendChild(a);for(a=-3;3>=a;a+=1){var d=document.createElementNS("http://www.w3.org/2000/svg","line");d.setAttribute("x1",a);d.setAttribute("y1",-v-6-
4);d.setAttribute("x2",a);d.setAttribute("y2",-v-6);d.style.strokeWidth=.2;d.style.stroke="black";l().appendChild(d)}for(a=0;12>a;++a){var d=document.createElementNS("http://www.w3.org/2000/svg","line"),n=a/12*2*Math.PI,p=v,t=.7*v;d.setAttribute("x1",p*Math.sin(n));d.setAttribute("y1",-p*Math.cos(n));d.setAttribute("x2",t*Math.sin(n));d.setAttribute("y2",-t*Math.cos(n));d.style.strokeWidth=1;d.style.stroke="black";l().appendChild(d)}for(a=0;60>a;++a)d=document.createElementNS("http://www.w3.org/2000/svg",
"line"),n=a/60*2*Math.PI,p=v,t=.85*v,d.setAttribute("x1",p*Math.sin(n)),d.setAttribute("y1",-p*Math.cos(n)),d.setAttribute("x2",t*Math.sin(n)),d.setAttribute("y2",-t*Math.cos(n)),d.style.strokeWidth=.5,d.style.stroke="black",l().appendChild(d);a=document.createElementNS("http://www.w3.org/2000/svg","line");a.id=q+"Hand";a.setAttribute("x1",0);a.setAttribute("y1",0);a.setAttribute("x2",0);a.setAttribute("y2",.8*-v);a.style.strokeWidth=1.5;a.style.stroke="black";l().appendChild(a);l().style.visibility=
"hidden"})()};String.prototype.endsWith||(String.prototype.endsWith=function(q,l){var d=this.toString();if(void 0===l||l>d.length)l=d.length;l-=q.length;d=d.indexOf(q,l);return-1!==d&&d===l});
function Game(q,l,d){function x(a,h,d,e,g,l,m){var n=new XMLHttpRequest;n.onreadystatechange=function(){if(4==n.readyState){var a=b.indexOf(d);if(-1!=a){b.splice(a,1);for(var c=f+1;c<=C;++c)if(a=b.indexOf(c),-1==a)f=c;else break;requestResolved=!0}else requestResolved=!1;200<=n.status&&299>=n.status?requestResolved||C==d?l(n.responseText):console.log("Dropped response from an old request."):m&&m(n.responseText)}};n.open(a,h,!0);e&&n.setRequestHeader("Content-type",e);g?n.send(g):n.send()}function v(a,
h,d,e){++C;b.push(C);x("POST",a,C,"application/x-www-form-urlencoded; charset=UTF-8",h,d,e)}function p(a){if("fail"==a)alert("Operation failed");else try{var b=JSON.parse(a);b.gameinfo&&("success"!==b.status&&console.log("last update failed"),b=b.gameinfo);d=b;E()}catch(e){console.log("Unrecognized server response: "+a)}}function n(a){a=a.split("/");for(var b=[],d=1;d<a.length;++d){var e=a[d];if("R"==e||"B"==e)break;b.push([parseInt(e[0],10),parseInt(e[1],10),parseInt(e[2],10),parseInt(e[3],10)])}return b}
function a(a,b,e,f){var g=d;a=[a,b,e,f];g.moves+="/"+(""+a[0]+a[1]+a[2]+a[3]);H();v("/gameinfo","uid="+l+"&sid="+F("sid")+"&gid="+q+"&moves="+d.moves,p,B);G()}function B(a){console.log("Retrieve game info failed")}function F(a){a+="=";for(var b=document.cookie.split(";"),d=0;d<b.length;++d){for(var e=b[d];" "==e.charAt(0);)e=e.substring(1);if(0==e.indexOf(a))return e.substring(a.length,e.length)}return""}function A(a){var b=document.getElementById(a+"-player"),d=document.getElementById(a+"-sit-link");
b.removeChild(d);b.appendChild(document.createTextNode("sitting down..."));v("/gameinfo","uid="+l+"&sid="+F("sid")+"&gid="+q+"&sit="+a,p,B)}function t(a,b,d,e,f){var g=document.createElement("a");g.id=a;b&&(g.className=b);g.href=d;e&&(g.onclick=e);g.appendChild(document.createTextNode(f));return g}function g(a){var b=document.createElement("sup");b.className="hint-you";a?b.appendChild(document.createTextNode(" ")):b.appendChild(document.createTextNode("you"));return b}function D(){removeAllChildren("red-player");
removeAllChildren("black-player");if(void 0!==d.red&&null!==d.red){var a=document.getElementById("red-player"),b=document.createElement("span");b.appendChild(document.createTextNode(d.red.name));a.appendChild(b);a.appendChild(g(d.red.id!=l))}else b=t("red-sit-link","sit-link","#",function(){A("red");return!1},"sit here"),document.getElementById("red-player").appendChild(b);void 0!==d.black&&null!==d.black?(a=document.getElementById("black-player"),b=document.createElement("span"),b.appendChild(document.createTextNode(d.black.name)),
a.appendChild(b),a.appendChild(g(d.black.id!=l))):(b=t("black-sit-link","sit-link","#",function(){A("black");return!1},"sit here"),document.getElementById("black-player").appendChild(b))}function H(){var a=document.getElementById("waitingStatus"),b=document.getElementById("playingStatus"),f=document.getElementById("redWonStatus"),g=document.getElementById("blackWonStatus");a.style.display="none";b.style.display="none";f.style.display="none";g.style.display="none";d.moves.endsWith("R")?f.style.display=
"inline-block":d.moves.endsWith("B")?g.style.display="inline-block":d.red&&d.black?(b.style.display="inline-block",e.isRedNext()?(y.start(),m.stop()):(m.start(),y.stop())):a.style.display="inline-block"}function z(a,b){var d=document.createElement("td");d.appendChild(b);a.appendChild(d)}function G(){removeAllChildren("move-history");var a=document.getElementById("move-history"),b=document.createElement("table");b.id="moveHistoryControls";var d=document.createElement("tr");b.appendChild(d);0<e.numMovesShown()?
(z(d,t("move-history-first",void 0,"#",function(){e.showMove(0);G();return!1},"first")),z(d,t("move-history-prev",void 0,"#",function(){e.showMove(e.numMovesShown()-1);G();return!1},"prev"))):(z(d,document.createTextNode("first")),z(d,document.createTextNode("prev")));z(d,document.createTextNode(""+e.numMovesShown()+" / "+e.numMoves()));e.numMovesShown()<e.numMoves()?(z(d,t("move-history-next",void 0,"#",function(){e.showMove(e.numMovesShown()+1);G();return!1},"next")),z(d,t("move-history-last",void 0,
"#",function(){e.showMove(e.numMoves());G();return!1},"last"))):(z(d,document.createTextNode("next")),z(d,document.createTextNode("last")));a.appendChild(b);document.getElementById("forkGame");removeAllChildren("forkGame");forkGame.appendChild(t("move-history-fork-link",void 0,"/fork/"+q+"/"+e.numMovesShown().toString(),void 0,"fork at move "+e.numMovesShown()))}function E(){D();var a="r";d.black&&d.black.id==l&&(a="b");var b=d.black&&d.black.id==l||d.red&&d.red.id==l;e.setState(a,!(d.red&&d.black&&
!d.moves.endsWith("R")&&!d.moves.endsWith("B"))||!b,n(d.moves));H();G()}function u(){var a=document.getElementById("board");.81*window.innerHeight<=window.innerWidth?(a.style.removeProperty("width"),a.style.height="90vh"):(a.style.width="100vw",a.style.removeProperty("height"))}var y,m,e,f=0,C=0,b=[];(function(){y=new Stopwatch("redStopwatch");m=new Stopwatch("blackStopwatch");window.setInterval(function(){y.tick();m.tick()},6E4/y.frequency());window.onload=u;window.onresize=u;e=new Board(a);E();
window.setInterval(function(){x("GET","/gameinfo?gid="+q,f,void 0,void 0,p,B)},1E3)})()}function toggleMenu(){var q=document.getElementById("menu-text"),l=document.getElementById("menu-content");"grid"==l.style.display?(l.style.display="none",q.innerHTML='menu <span class="menu-toggle">[+]</span>'):(l.style.display="grid",q.innerHTML='menu <span class="menu-toggle">[-]</span>')}document.onreadystatechange=function(){"interactive"==document.readyState&&new Game(currentGameId,myUid,gameInfo)};
